# -*- coding: utf-8 -*-
"""CvsFV_Plot_Production

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xgtu4JEqLY5IhZdZ8SGQWFXmfQUfjNCq
"""

"""
Fourier-feature-number sensitivity study for TO-NN / TOuNN-FF.

This program loops over different numbers of Fourier feature vectors:
    16, 32, 64, 128, 256, 512, 1024

For each run, it trains a separate density network and saves:
    - final coarse density plot
    - final high-resolution raw density plot
    - training history plot

No evolution GIF is generated.

Each saved filename includes:
    FFd{num_fourier_features}_FFsigma{sigma}_{Problem}_TM{nelx}X{nely}_VF{volfrac}

Each density plot title also includes the final compliance number.
"""

# ============================================================
# Block 1 - Imports
# ============================================================
from dataclasses import dataclass, replace
from pathlib import Path
import math
import sys
import gc
import copy

import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

try:
    from IPython.display import display
except Exception:
    display = None


gc.collect()
torch.cuda.empty_cache()

if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
    print(torch.cuda.memory_summary(device=0, abbreviated=True))


# ============================================================
# Block 2 - Configuration
# ============================================================
@dataclass
class Config:
    # Domain and benchmark
    nelx: int = 100
    nely: int = 50
    lx: float = 2.0
    ly: float = 1.0
    volfrac: float = 0.4
    problem_name: str = "Tip_loaded_cantilever"   # "Tip_loaded_cantilever", "Mid_loaded_cantilever", "MBB"

    # Material / FE
    E0: float = 1.0
    Emin: float = 1e-9
    nu: float = 0.3
    plane_stress: bool = True
    penal: float = 3.0

    # Fourier-feature INR
    num_fourier_features: int = 512
    fourier_sigma: float = 1.0
    fourier_seed: int = 0

    # Decoder MLP
    num_hidden_layers: int = 4
    hidden_width: int = 512

    # Optimizer
    lr: float = 1e-3
    max_epochs: int = 1000

    # One-sided ALM settings for V(rho) <= V0
    alm_lambda0: float = 0.0
    alm_mu0: float = 5.0
    alm_update_every: int = 50
    alm_mu_scale: float = 1.2
    alm_mu_max: float = 50.0

    # Stopping rule
    rho_change_max_tol: float = 0.05
    volfrac_residual_tol: float = 0.001
    compliance_rel_improve_tol: float = 5e-4
    compliance_window: int = 10
    patience: int = 5
    min_epochs_before_stop: int = 100

    # High-resolution output
    samples_per_element: int = 15

    # Sensitivity study
    fourier_feature_list: tuple = (16, 32, 64, 128, 256, 512, 1024)

    # Misc
    print_every: int = 50
    save_outputs: bool = True
    out_dir: str = "/content/tounn_fourier_feature_sensitivity_outputs"
    device: str = "auto"
    dtype: torch.dtype = torch.float32


# ============================================================
# Block 3 - Runtime helpers
# ============================================================
def resolve_device(device_string: str) -> torch.device:
    if device_string == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device_string == "cuda" and not torch.cuda.is_available():
        print("Requested CUDA, but no GPU is available. Falling back to CPU.")
        return torch.device("cpu")
    return torch.device(device_string)


def running_in_colab() -> bool:
    return "google.colab" in sys.modules


def safe_logit(p: float, eps: float = 1e-6) -> float:
    p = float(np.clip(p, eps, 1.0 - eps))
    return math.log(p / (1.0 - p))


def make_problem_tag(problem_name: str) -> str:
    if problem_name == "Tip_loaded_cantilever":
        return "Tip_loaded_Cantilever"
    if problem_name == "Mid_loaded_cantilever":
        return "Mid_loaded_Cantilever"
    if problem_name == "MBB":
        return "MBB"
    return problem_name.strip().replace(" ", "_")


def make_run_tag(cfg: Config) -> str:
    problem_tag = make_problem_tag(cfg.problem_name)
    d_tag = f"FFd{cfg.num_fourier_features:g}"
    sigma_tag = f"FFsigma{cfg.fourier_sigma:g}"
    mesh_tag = f"TM{cfg.nelx}X{cfg.nely}"
    vf_tag = f"VF{cfg.volfrac:g}"
    return f"{d_tag}_{sigma_tag}_{problem_tag}_{mesh_tag}_{vf_tag}"


def make_compliance_tag(compliance: float) -> str:
    return f"C{compliance:.3f}".replace(".", "p")


def clear_memory():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


# ============================================================
# Block 4 - Mesh, BCs, and Q4 FE helpers
# ============================================================
def node_id(ix, iy, nelx):
    return iy * (nelx + 1) + ix


def q4_element_stiffness_rect(dx, dy, nu, plane_stress=True):
    if plane_stress:
        D = (1.0 / (1.0 - nu**2)) * np.array([
            [1.0, nu, 0.0],
            [nu, 1.0, 0.0],
            [0.0, 0.0, (1.0 - nu) / 2.0],
        ], dtype=float)
    else:
        D = ((1.0 - nu) / ((1.0 + nu) * (1.0 - 2.0 * nu))) * np.array([
            [1.0, nu / (1.0 - nu), 0.0],
            [nu / (1.0 - nu), 1.0, 0.0],
            [0.0, 0.0, (1.0 - 2.0 * nu) / (2.0 * (1.0 - nu))],
        ], dtype=float)

    xnod = np.array([-dx / 2, dx / 2, dx / 2, -dx / 2], dtype=float)
    ynod = np.array([-dy / 2, -dy / 2, dy / 2, dy / 2], dtype=float)

    gp = 1.0 / np.sqrt(3.0)
    gauss_points = [(-gp, -gp), (gp, -gp), (gp, gp), (-gp, gp)]
    KE = np.zeros((8, 8), dtype=float)

    for xi, eta in gauss_points:
        dN_dxi = 0.25 * np.array([
            -(1.0 - eta),
             (1.0 - eta),
             (1.0 + eta),
            -(1.0 + eta),
        ], dtype=float)

        dN_deta = 0.25 * np.array([
            -(1.0 - xi),
            -(1.0 + xi),
             (1.0 + xi),
             (1.0 - xi),
        ], dtype=float)

        J = np.array([
            [np.dot(dN_dxi, xnod), np.dot(dN_deta, xnod)],
            [np.dot(dN_dxi, ynod), np.dot(dN_deta, ynod)],
        ], dtype=float)

        invJ = np.linalg.inv(J)
        dN = np.vstack((dN_dxi, dN_deta))
        dN_xy = invJ @ dN

        dN_dx = dN_xy[0, :]
        dN_dy = dN_xy[1, :]
        detJ = np.linalg.det(J)

        B = np.zeros((3, 8), dtype=float)
        for a in range(4):
            B[0, 2 * a] = dN_dx[a]
            B[1, 2 * a + 1] = dN_dy[a]
            B[2, 2 * a] = dN_dy[a]
            B[2, 2 * a + 1] = dN_dx[a]

        KE += B.T @ D @ B * detJ

    return KE


def get_loads_and_bcs(nelx, nely, problem_name):
    ndof = 2 * (nelx + 1) * (nely + 1)
    F = np.zeros(ndof, dtype=float)

    if problem_name == "Tip_loaded_cantilever":
        load_node = node_id(nelx, nely, nelx)
        F[2 * load_node + 1] = -1.0

        fixed = []
        for iy in range(nely + 1):
            n = node_id(0, iy, nelx)
            fixed.extend([2 * n, 2 * n + 1])

    elif problem_name == "Mid_loaded_cantilever":
        load_node = node_id(nelx, nely // 2, nelx)
        F[2 * load_node + 1] = -1.0

        fixed = []
        for iy in range(nely + 1):
            n = node_id(0, iy, nelx)
            fixed.extend([2 * n, 2 * n + 1])

    elif problem_name == "MBB":
        load_node = node_id(0, nely, nelx)
        F[2 * load_node + 1] = -1.0

        fixed = []
        for iy in range(nely + 1):
            n = node_id(0, iy, nelx)
            fixed.append(2 * n)

        br = node_id(nelx, 0, nelx)
        fixed.append(2 * br + 1)

    else:
        raise ValueError("Unknown problem_name")

    fixed = np.array(sorted(set(fixed)), dtype=int)
    free = np.setdiff1d(np.arange(ndof), fixed)

    return F, fixed, free


def build_problem_data(cfg):
    nelx, nely = cfg.nelx, cfg.nely
    dx = cfg.lx / nelx
    dy = cfg.ly / nely

    nele = nelx * nely
    ndof = 2 * (nelx + 1) * (nely + 1)

    centers = np.zeros((nele, 2), dtype=float)
    elem_areas = np.full(nele, dx * dy, dtype=float)
    edofMat = np.zeros((nele, 8), dtype=int)

    e = 0
    for ey in range(nely):
        for ex in range(nelx):
            centers[e, :] = [(ex + 0.5) * dx, (ey + 0.5) * dy]

            n1 = node_id(ex, ey, nelx)
            n2 = node_id(ex + 1, ey, nelx)
            n3 = node_id(ex + 1, ey + 1, nelx)
            n4 = node_id(ex, ey + 1, nelx)

            edofMat[e, :] = [
                2 * n1, 2 * n1 + 1,
                2 * n2, 2 * n2 + 1,
                2 * n3, 2 * n3 + 1,
                2 * n4, 2 * n4 + 1,
            ]

            e += 1

    iK = np.kron(edofMat, np.ones((8, 1), dtype=int)).ravel()
    jK = np.kron(edofMat, np.ones((1, 8), dtype=int)).ravel()

    KE = q4_element_stiffness_rect(dx, dy, cfg.nu, cfg.plane_stress)
    F, fixed, free = get_loads_and_bcs(nelx, nely, cfg.problem_name)

    return {
        "centers": centers,
        "elem_areas": elem_areas,
        "edofMat": edofMat,
        "iK": iK,
        "jK": jK,
        "KE": KE,
        "F": F,
        "fixed": fixed,
        "free": free,
        "ndof": ndof,
        "nele": nele,
        "dx": dx,
        "dy": dy,
    }


# ============================================================
# Block 5 - FEA black box
# ============================================================
def fea_black_box(rho_torch, problem_data, cfg):
    rho = rho_torch.detach().cpu().numpy().astype(float)
    rho = np.clip(rho, 1e-9, 1.0)

    E_e = cfg.Emin + (rho ** cfg.penal) * (cfg.E0 - cfg.Emin)
    sK = np.outer(E_e, problem_data["KE"].ravel()).ravel()

    K = sp.coo_matrix(
        (sK, (problem_data["iK"], problem_data["jK"])),
        shape=(problem_data["ndof"], problem_data["ndof"]),
    ).tocsc()

    K = 0.5 * (K + K.T)

    U = np.zeros(problem_data["ndof"], dtype=float)
    free = problem_data["free"]

    U[free] = spla.spsolve(K[free, :][:, free], problem_data["F"][free])

    Ue = U[problem_data["edofMat"]]
    Je0 = np.einsum("ij,ij->i", Ue @ problem_data["KE"], Ue)

    compliance = np.sum(E_e * Je0)

    return Je0, float(compliance)


def compute_windowed_compliance_improvement(compliance_history, window):
    if len(compliance_history) < 2 * window:
        return np.inf

    older = np.mean(compliance_history[-2 * window:-window])
    recent = np.mean(compliance_history[-window:])

    return abs(recent - older) / max(abs(older), 1e-12)


# ============================================================
# Block 6 - Fourier feature density network
# ============================================================
class FourierFeatureMap(nn.Module):
    def __init__(self, in_dim: int, num_fourier_features: int, sigma: float, seed: int = 0):
        super().__init__()

        gen = torch.Generator(device="cpu")
        gen.manual_seed(seed)

        B = torch.randn((num_fourier_features, in_dim), generator=gen) * sigma
        self.register_buffer("B", B)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        xb = 2.0 * math.pi * (x @ self.B.T)
        return torch.cat([torch.cos(xb), torch.sin(xb)], dim=1)


class PaperStyleFourierDensityNet(nn.Module):
    def __init__(self, cfg: Config):
        super().__init__()

        self.fourier = FourierFeatureMap(
            in_dim=2,
            num_fourier_features=cfg.num_fourier_features,
            sigma=cfg.fourier_sigma,
            seed=cfg.fourier_seed,
        )

        input_dim = 2 * cfg.num_fourier_features
        in_dim = input_dim

        self.hidden_linears = nn.ModuleList()

        for _ in range(cfg.num_hidden_layers):
            linear = nn.Linear(in_dim, cfg.hidden_width)
            self.hidden_linears.append(linear)
            in_dim = cfg.hidden_width

        self.out = nn.Linear(in_dim, 1)

        # Hidden-layer activation
        self.activation = nn.LeakyReLU(negative_slope=0.01)

        self.reset_parameters(cfg.volfrac)

    def reset_parameters(self, volfrac: float):
        for linear in self.hidden_linears:
            nn.init.orthogonal_(linear.weight)
            nn.init.zeros_(linear.bias)

        nn.init.normal_(self.out.weight, mean=0.0, std=1e-4)
        nn.init.constant_(self.out.bias, safe_logit(volfrac))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        z = self.fourier(x)

        h = z
        for linear in self.hidden_linears:
            h = self.activation(linear(h))

        logits = self.out(h)

        return torch.sigmoid(logits).squeeze(1)


# ============================================================
# Block 7 - High-resolution sampling
# ============================================================
def sample_highres_density(model, cfg, device):
    s = cfg.samples_per_element

    nx_hr = cfg.nelx * s
    ny_hr = cfg.nely * s

    dx_hr = cfg.lx / nx_hr
    dy_hr = cfg.ly / ny_hr

    xs = (np.arange(nx_hr) + 0.5) * dx_hr
    ys = (np.arange(ny_hr) + 0.5) * dy_hr

    XX, YY = np.meshgrid(xs, ys)
    pts = np.column_stack([XX.ravel(), YY.ravel()])

    with torch.no_grad():
        model.eval()
        pts_t = torch.tensor(pts, dtype=cfg.dtype, device=device)
        rho_hr = model(pts_t).detach().cpu().numpy().reshape(ny_hr, nx_hr)

    return rho_hr


# ============================================================
# Block 8 - Training loop
# ============================================================
def train(cfg):
    device = resolve_device(cfg.device)
    problem_data = build_problem_data(cfg)

    coords = torch.tensor(problem_data["centers"], dtype=cfg.dtype, device=device)
    elem_areas = torch.tensor(problem_data["elem_areas"], dtype=cfg.dtype, device=device)

    V_total = float(problem_data["elem_areas"].sum())
    V_star_abs = cfg.volfrac * V_total

    model = PaperStyleFourierDensityNet(cfg).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg.lr)

    previous_rho = None
    patience_counter = 0

    alm_lambda = float(cfg.alm_lambda0)
    alm_mu = float(cfg.alm_mu0)
    prev_g_plus_for_mu = None

    J0 = None

    history = {
        "epoch": [],
        "compliance": [],
        "volfrac": [],
        "loss": [],
        "rho_change_max": [],
        "volfrac_residual": [],
        "compliance_rel_improve": [],
        "patience_counter": [],
        "alm_lambda": [],
        "alm_mu": [],
        "g_plus": [],
    }

    run_tag = make_run_tag(cfg)

    print("=" * 88)
    print("Fourier-feature-number sensitivity run")
    print(f"Run tag                   : {run_tag}")
    print(f"Device                    : {device}")
    print(f"Problem                   : {cfg.problem_name}")
    print(f"Mesh                      : {cfg.nelx} x {cfg.nely}")
    print(f"Domain                    : {cfg.lx} x {cfg.ly}")
    print(f"Target volfrac            : {cfg.volfrac}")
    print(f"SIMP penal                : {cfg.penal}")
    print(f"Fourier features d        : {cfg.num_fourier_features}")
    print(f"Fixed sigma               : {cfg.fourier_sigma}")
    print(f"Decoder layers / width    : {cfg.num_hidden_layers} / {cfg.hidden_width}")
    print(f"Activation                : LeakyReLU, slope = 0.01")
    print(f"Adam lr                   : {cfg.lr}")
    print(f"Max iterations            : {cfg.max_epochs}")
    print(f"Stopping window/patience  : {cfg.compliance_window} / {cfg.patience}")
    print(f"ALM lambda0 / mu0         : {cfg.alm_lambda0} / {cfg.alm_mu0}")
    print(f"ALM update every          : {cfg.alm_update_every}")
    print("=" * 88)

    for epoch in range(cfg.max_epochs):
        model.train()
        optimizer.zero_grad()

        rho = model(coords).clamp(1e-6, 1.0 - 1e-6)

        Je0_np, compliance = fea_black_box(rho, problem_data, cfg)
        Je0 = torch.tensor(Je0_np, dtype=cfg.dtype, device=device)

        V_abs = torch.sum(rho * elem_areas)
        volfrac_current = V_abs / V_total
        volfrac_residual = volfrac_current / cfg.volfrac - 1.0

        g_v = (V_abs / V_star_abs) - 1.0
        g_plus = torch.clamp(g_v, min=0.0)

        if epoch == 0:
            J0 = max(float(compliance), 1e-12)

        loss = (compliance / J0) + alm_lambda * g_plus + 0.5 * alm_mu * (g_plus ** 2)

        dJ_drho = (
            -cfg.penal
            * (cfg.E0 - cfg.Emin)
            * torch.pow(rho.detach(), cfg.penal - 1.0)
            * Je0
            / J0
        )

        dVabs_drho = elem_areas
        dg_drho = dVabs_drho / V_star_abs

        active_mask = (g_v.detach() > 0.0).to(cfg.dtype)

        dL_drho = dJ_drho + (
            alm_lambda + alm_mu * g_plus.detach()
        ) * active_mask * dg_drho

        rho.backward(dL_drho)
        optimizer.step()

        if (epoch + 1) % cfg.alm_update_every == 0:
            g_scalar = float(g_v.detach().cpu())
            g_plus_scalar = max(g_scalar, 0.0)

            alm_lambda = max(0.0, alm_lambda + alm_mu * g_scalar)

            if prev_g_plus_for_mu is not None and g_plus_scalar > 0.25 * prev_g_plus_for_mu:
                alm_mu = min(cfg.alm_mu_max, alm_mu * cfg.alm_mu_scale)

            prev_g_plus_for_mu = g_plus_scalar

        rho_cpu = rho.detach().cpu().numpy()

        if previous_rho is None:
            rho_change_max = np.inf
        else:
            rho_change_max = float(np.max(np.abs(rho_cpu - previous_rho)))

        previous_rho = rho_cpu.copy()

        history["epoch"].append(epoch)
        history["compliance"].append(float(compliance))
        history["volfrac"].append(float(volfrac_current.detach().cpu()))
        history["loss"].append(float(loss.detach().cpu()))
        history["rho_change_max"].append(rho_change_max)
        history["volfrac_residual"].append(float(volfrac_residual.detach().cpu()))
        history["alm_lambda"].append(float(alm_lambda))
        history["alm_mu"].append(float(alm_mu))
        history["g_plus"].append(float(g_plus.detach().cpu()))

        compliance_rel_improve = compute_windowed_compliance_improvement(
            history["compliance"],
            cfg.compliance_window,
        )

        history["compliance_rel_improve"].append(compliance_rel_improve)

        enough_epochs = epoch >= cfg.min_epochs_before_stop
        volume_ok = abs(float(volfrac_residual.detach().cpu())) < cfg.volfrac_residual_tol
        rho_ok = rho_change_max < cfg.rho_change_max_tol
        compliance_ok = compliance_rel_improve < cfg.compliance_rel_improve_tol

        if enough_epochs and volume_ok and rho_ok and compliance_ok:
            patience_counter += 1
        else:
            patience_counter = 0

        history["patience_counter"].append(patience_counter)

        if epoch % cfg.print_every == 0 or epoch == cfg.max_epochs - 1:
            improve_str = f"{compliance_rel_improve:9.3e}" if np.isfinite(compliance_rel_improve) else "      inf"

            print(
                f"iter={epoch:5d} | "
                f"Lt={float(loss.detach().cpu()):12.5f} | "
                f"J={float(compliance):12.5f} | "
                f"VF={float(volfrac_current.detach().cpu()):7.4f} | "
                f"gVF={float(volfrac_residual.detach().cpu()):+9.5f} | "
                f"g+={float(g_plus.detach().cpu()):10.4e} | "
                f"lam={float(alm_lambda):10.4e} | "
                f"mu={float(alm_mu):10.4e} | "
                f"max|dRho|={rho_change_max:9.3e} | "
                f"rel dC={improve_str} | "
                f"vol_ok={volume_ok} | "
                f"rho_ok={rho_ok} | "
                f"comp_ok={compliance_ok} | "
                f"pat={patience_counter:3d}/{cfg.patience:3d}"
            )

        if patience_counter >= cfg.patience:
            print("\nConverged with sustained density/design stabilization.")
            print(f"Stopped at iteration       : {epoch}")
            print(f"Final compliance           : {compliance:.6f}")
            print(f"max|rho_k-rho_k-1|         : {rho_change_max:.6e}")
            print(f"|volume residual|          : {abs(float(volfrac_residual.detach().cpu())):.6e}")
            print(f"windowed rel compliance Δ  : {compliance_rel_improve:.6e}")
            break

    return model, history, problem_data, device


# ============================================================
# Block 9 - Plotting and saving
# ============================================================
def get_final_density(model, cfg, problem_data, device):
    coords = torch.tensor(problem_data["centers"], dtype=cfg.dtype, device=device)

    with torch.no_grad():
        model.eval()
        rho = model(coords).detach().cpu().numpy().reshape(cfg.nely, cfg.nelx)

    return rho


def save_results_for_single_run(model, history, cfg, problem_data, device):
    out_dir = Path(cfg.out_dir)
    run_tag = make_run_tag(cfg)

    if cfg.save_outputs:
        out_dir.mkdir(parents=True, exist_ok=True)

    final_compliance = float(history["compliance"][-1])
    final_vf = float(history["volfrac"][-1])
    final_epoch = int(history["epoch"][-1])
    c_tag = make_compliance_tag(final_compliance)

    rho = get_final_density(model, cfg, problem_data, device)
    rho_hr = sample_highres_density(model, cfg, device)

    coarse_path = out_dir / f"{run_tag}_final_density_coarse_{c_tag}.png"
    highres_path = out_dir / f"{run_tag}_final_highres_raw_{c_tag}.png"
    history_path = out_dir / f"{run_tag}_training_history_{c_tag}.png"

    plt.figure(figsize=(9, 4))
    plt.imshow(
        rho,
        cmap="gray_r",
        origin="lower",
        extent=[0, cfg.lx, 0, cfg.ly],
        aspect="equal",
    )
    plt.colorbar(label="Density")
    plt.xlabel("x")
    plt.ylabel("y")
    plt.title(
        f"Final coarse density | {cfg.problem_name} | FE {cfg.nelx}x{cfg.nely} | "
        f"FF d={cfg.num_fourier_features}, sigma={cfg.fourier_sigma:g} | "
        f"C={final_compliance:.3f}"
    )
    plt.tight_layout()

    if cfg.save_outputs:
        plt.savefig(coarse_path, dpi=250, bbox_inches="tight")

    plt.show()
    plt.close()

    plt.figure(figsize=(9, 4))
    plt.imshow(
        rho_hr,
        cmap="gray_r",
        origin="lower",
        vmin=0.0,
        vmax=1.0,
        extent=[0, cfg.lx, 0, cfg.ly],
        aspect="equal",
        interpolation="nearest",
    )
    plt.colorbar(label="Density")
    plt.xlabel("x")
    plt.ylabel("y")
    plt.title(
        f"Final high-res raw density | {cfg.problem_name} | "
        f"FF d={cfg.num_fourier_features}, sigma={cfg.fourier_sigma:g} | "
        f"C={final_compliance:.3f}"
    )
    plt.tight_layout()

    if cfg.save_outputs:
        plt.savefig(highres_path, dpi=250, bbox_inches="tight")

    plt.show()
    plt.close()

    fig, axs = plt.subplots(6, 1, figsize=(10, 16), sharex=True)

    axs[0].plot(history["epoch"], history["loss"])
    axs[0].set_ylabel("Total loss")
    axs[0].grid(True, alpha=0.3)
    axs[0].set_title(
        f"Training history | FF d={cfg.num_fourier_features}, sigma={cfg.fourier_sigma:g} | "
        f"Final C={final_compliance:.3f}, VF={final_vf:.4f}, epoch={final_epoch}"
    )

    axs[1].plot(history["epoch"], history["compliance"])
    axs[1].set_ylabel("Compliance")
    axs[1].grid(True, alpha=0.3)

    axs[2].plot(history["epoch"], history["volfrac"])
    axs[2].axhline(cfg.volfrac, linestyle="--")
    axs[2].set_ylabel("Current VF")
    axs[2].grid(True, alpha=0.3)

    axs[3].plot(history["epoch"], history["rho_change_max"])
    axs[3].axhline(cfg.rho_change_max_tol, linestyle="--")
    axs[3].set_ylabel("max|Δrho|")
    axs[3].set_yscale("log")
    axs[3].grid(True, alpha=0.3)

    axs[4].plot(history["epoch"], history["g_plus"], label="g+")
    axs[4].plot(history["epoch"], history["alm_lambda"], label="lambda")
    axs[4].plot(history["epoch"], history["alm_mu"], label="mu")
    axs[4].set_ylabel("ALM control")
    axs[4].set_yscale("log")
    axs[4].grid(True, alpha=0.3)
    axs[4].legend()

    comp_improve = np.array(history["compliance_rel_improve"], dtype=float)
    comp_improve_plot = comp_improve.copy()
    comp_improve_plot[~np.isfinite(comp_improve_plot)] = np.nan

    axs[5].plot(history["epoch"], comp_improve_plot, label="rel compliance change")
    axs[5].axhline(cfg.compliance_rel_improve_tol, linestyle="--", label="tolerance")
    axs[5].plot(history["epoch"], history["patience_counter"], label="patience counter")
    axs[5].set_ylabel("Convergence")
    axs[5].set_xlabel("Iteration")
    axs[5].set_yscale("log")
    axs[5].grid(True, alpha=0.3)
    axs[5].legend()

    fig.tight_layout()

    if cfg.save_outputs:
        fig.savefig(history_path, dpi=250, bbox_inches="tight")

    plt.show()
    plt.close(fig)

    result_row = {
        "num_fourier_features": cfg.num_fourier_features,
        "fourier_sigma": cfg.fourier_sigma,
        "final_compliance": final_compliance,
        "final_volfrac": final_vf,
        "final_epoch": final_epoch,
        "final_rho_change_max": float(history["rho_change_max"][-1]),
        "final_volfrac_residual": float(history["volfrac_residual"][-1]),
        "final_compliance_rel_improve": float(history["compliance_rel_improve"][-1]),
        "coarse_path": str(coarse_path),
        "highres_path": str(highres_path),
        "history_path": str(history_path),
    }

    if cfg.save_outputs:
        print("\nSaved outputs:")
        print(coarse_path)
        print(highres_path)
        print(history_path)

    return result_row


def save_sensitivity_summary(results, base_cfg):
    out_dir = Path(base_cfg.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    summary_path = out_dir / (
        f"FourierFeatureSensitivity_FFsigma{base_cfg.fourier_sigma:g}_"
        f"{make_problem_tag(base_cfg.problem_name)}_TM{base_cfg.nelx}X{base_cfg.nely}_"
        f"VF{base_cfg.volfrac:g}_summary.csv"
    )

    headers = [
        "num_fourier_features",
        "fourier_sigma",
        "final_compliance",
        "final_volfrac",
        "final_epoch",
        "final_rho_change_max",
        "final_volfrac_residual",
        "final_compliance_rel_improve",
        "coarse_path",
        "highres_path",
        "history_path",
    ]

    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(",".join(headers) + "\n")
        for row in results:
            f.write(",".join(str(row[h]) for h in headers) + "\n")

    print("\nSensitivity summary saved to:")
    print(summary_path)

    return summary_path


def plot_sensitivity_compliance_summary(results, base_cfg):
    out_dir = Path(base_cfg.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    d_values = [r["num_fourier_features"] for r in results]
    c_values = [r["final_compliance"] for r in results]

    fig_path = out_dir / (
        f"FourierFeatureSensitivity_FFsigma{base_cfg.fourier_sigma:g}_"
        f"{make_problem_tag(base_cfg.problem_name)}_TM{base_cfg.nelx}X{base_cfg.nely}_"
        f"VF{base_cfg.volfrac:g}_compliance_summary.png"
    )

    plt.figure(figsize=(8, 5))
    plt.plot(d_values, c_values, marker="o")
    plt.xscale("log", base=2)
    plt.xlabel("Number of Fourier feature vectors, d")
    plt.ylabel("Final compliance")
    plt.title(
        f"Sensitivity to Fourier feature dimension | sigma={base_cfg.fourier_sigma:g} | "
        f"{base_cfg.problem_name} | FE {base_cfg.nelx}x{base_cfg.nely}"
    )
    plt.grid(True, alpha=0.3)
    plt.tight_layout()

    if base_cfg.save_outputs:
        plt.savefig(fig_path, dpi=250, bbox_inches="tight")

    plt.show()
    plt.close()

    print("\nCompliance sensitivity plot saved to:")
    print(fig_path)

    return fig_path


# ============================================================
# Block 10 - Main sensitivity-study run cell
# ============================================================
def main():
    base_cfg = Config(
        device="auto",
        out_dir="/content/tounn_fourier_feature_sensitivity_outputs",
    )

    results = []

    for d in base_cfg.fourier_feature_list:
        print("\n\n")
        print("#" * 100)
        print(f"Starting Fourier-feature sensitivity case: d = {d}")
        print("#" * 100)

        cfg = replace(base_cfg, num_fourier_features=d)

        clear_memory()

        model, history, problem_data, device = train(cfg)

        result_row = save_results_for_single_run(
            model=model,
            history=history,
            cfg=cfg,
            problem_data=problem_data,
            device=device,
        )

        results.append(result_row)

        del model
        del history
        del problem_data

        clear_memory()

    save_sensitivity_summary(results, base_cfg)
    plot_sensitivity_compliance_summary(results, base_cfg)

    print("\nCompleted Fourier-feature-number sensitivity study.")
    print("Summary of final compliance values:")
    for row in results:
        print(
            f"d={row['num_fourier_features']:4d} | "
            f"C={row['final_compliance']:12.5f} | "
            f"VF={row['final_volfrac']:.5f} | "
            f"epoch={row['final_epoch']}"
        )


if __name__ == "__main__":
    main()