# -*- coding: utf-8 -*-
"""TONNFFBD_vs_TOP88_Study

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6tLtkOj6AiT_JN6UAqgbwmA0Ctbn4RN
"""

# ============================================================
# TONN-FFBD Batch Benchmark Study
# ============================================================
# Cases:
#   1) MBB
#   2) Tip_loaded_cantilever
#
# Study:
#   nelx x nely = 90 x 30
#   volfrac      = [0.2, 0.4, 0.6]
#   target minimum feature = 0.4 in
#
# Outputs:
#   Figure 1: three vertically stacked MBB final coarse topologies
#   Figure 2: three vertically stacked tip-loaded cantilever final coarse topologies
#
# Notes:
#   This script intentionally removes high-resolution reconstruction, GIFs,
#   and local thickness diagnostics so the output is limited to coarse final
#   optimized structures and final compliance values.
#
#   The volume constraint is enforced with an equality-style augmented
#   Lagrangian so the final compliance comparison is made at the intended
#   target volume fraction.
# ============================================================

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Any, List, Tuple
import math
import gc
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import matplotlib.pyplot as plt
import torch
import torch.nn as nn


gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    print(torch.cuda.get_device_name(0))


# ============================================================
# Configuration
# ============================================================

@dataclass
class Config:
    # Mesh and physical domain
    nelx: int = 90
    nely: int = 30
    elem_size_x: float = 0.1
    elem_size_y: float = 0.1

    # Study variables
    volfrac: float = 0.4
    problem_name: str = "MBB"

    # Material and SIMP
    E0: float = 1.0
    Emin: float = 1e-9
    nu: float = 0.3
    plane_stress: bool = True
    penal: float = 3.0

    # Bounded-disk Fourier features
    num_fourier_features: int = 512
    fourier_seed: int = 0
    target_min_length: float = 0.3

    # This keeps the same convention as your latest TONN-FFBD code.
    # Current rule: fmax = 1 / (6 * target_min_length).
    use_current_fmax_rule: bool = True

    # Neural network
    num_hidden_layers: int = 4
    hidden_width: int = 256

    # Optimizer
    lr: float = 1e-3
    max_epochs: int = 1000

    # Equality ALM for VF = target VF
    alm_lambda0: float = 0.0
    alm_mu0: float = 5
    alm_update_every: int = 50
    alm_mu_scale: float = 1.2
    alm_mu_max: float = 50

    # Stopping rule
    rho_change_max_tol: float = 0.05
    volfrac_residual_tol: float = 0.001
    compliance_rel_improve_tol: float = 1e-4
    compliance_window: int = 10
    patience: int = 20
    min_epochs_before_stop: int = 100

    # Misc
    print_every: int = 50
    save_figures: bool = True
    out_dir: str = "./tonn_ffbd_batch_outputs"
    device: str = "auto"
    dtype: torch.dtype = torch.float32

    @property
    def lx(self) -> float:
        return self.nelx * self.elem_size_x

    @property
    def ly(self) -> float:
        return self.nely * self.elem_size_y

    @property
    def fmax(self) -> float:
        if self.target_min_length <= 0.0:
            raise ValueError("target_min_length must be positive.")
        if self.use_current_fmax_rule:
            return 1.0 / (5.0 * self.target_min_length)
        return 1.0 / self.target_min_length

    @property
    def min_fourier_wavelength(self) -> float:
        return 1.0 / self.fmax


def resolve_device(device_string: str) -> torch.device:
    if device_string == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device_string == "cuda" and not torch.cuda.is_available():
        print("Requested CUDA, but CUDA is unavailable. Falling back to CPU.")
        return torch.device("cpu")
    return torch.device(device_string)


def safe_logit(p: float, eps: float = 1e-6) -> float:
    p = float(np.clip(p, eps, 1.0 - eps))
    return math.log(p / (1.0 - p))


# ============================================================
# Fourier feature map and neural density model
# ============================================================

class BoundedDiskFourierFeatureMap(nn.Module):
    def __init__(self, in_dim: int, num_fourier_features: int, fmax: float, seed: int = 0):
        super().__init__()
        if in_dim != 2:
            raise ValueError("This Fourier map assumes 2D coordinates.")
        if fmax <= 0.0:
            raise ValueError("fmax must be positive.")

        gen = torch.Generator(device="cpu")
        gen.manual_seed(seed)

        theta = 2.0 * math.pi * torch.rand(num_fourier_features, generator=gen)
        r = fmax * torch.rand(num_fourier_features, generator=gen)
        bx = r * torch.cos(theta)
        by = r * torch.sin(theta)
        B = torch.stack([bx, by], dim=1)

        self.fmax = fmax
        self.register_buffer("B", B)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        xb = 2.0 * math.pi * (x @ self.B.T)
        return torch.cat([torch.cos(xb), torch.sin(xb)], dim=1)


class FourierDensityNet(nn.Module):
    def __init__(self, cfg: Config):
        super().__init__()
        self.fourier = BoundedDiskFourierFeatureMap(
            in_dim=2,
            num_fourier_features=cfg.num_fourier_features,
            fmax=cfg.fmax,
            seed=cfg.fourier_seed,
        )

        in_dim = 2 * cfg.num_fourier_features
        self.hidden_linears = nn.ModuleList()
        for _ in range(cfg.num_hidden_layers):
            layer = nn.Linear(in_dim, cfg.hidden_width)
            self.hidden_linears.append(layer)
            in_dim = cfg.hidden_width

        self.out = nn.Linear(in_dim, 1)
        self.activation = nn.LeakyReLU(negative_slope=0.01)
        self.reset_parameters(cfg.volfrac)

    def reset_parameters(self, volfrac: float):
        for layer in self.hidden_linears:
            nn.init.orthogonal_(layer.weight)
            nn.init.zeros_(layer.bias)
        nn.init.normal_(self.out.weight, mean=0.0, std=1e-4)
        nn.init.constant_(self.out.bias, safe_logit(volfrac))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        z = self.fourier(x)
        h = z
        for layer in self.hidden_linears:
            h = self.activation(layer(h))
        logits = self.out(h)
        return torch.sigmoid(logits).squeeze(1)


# ============================================================
# Q4 FE helpers
# ============================================================

def node_id(ix: int, iy: int, nelx: int) -> int:
    return iy * (nelx + 1) + ix


def q4_element_stiffness_rect(dx: float, dy: float, nu: float, plane_stress: bool = True) -> np.ndarray:
    if plane_stress:
        D = (1.0 / (1.0 - nu**2)) * np.array([
            [1.0, nu, 0.0],
            [nu, 1.0, 0.0],
            [0.0, 0.0, (1.0 - nu) / 2.0],
        ], dtype=float)
    else:
        D = ((1.0 - nu) / ((1.0 + nu) * (1.0 - 2.0 * nu))) * np.array([
            [1.0, nu / (1.0 - nu), 0.0],
            [nu / (1.0 - nu), 1.0, 0.0],
            [0.0, 0.0, (1.0 - 2.0 * nu) / (2.0 * (1.0 - nu))],
        ], dtype=float)

    xnod = np.array([-dx / 2.0, dx / 2.0, dx / 2.0, -dx / 2.0], dtype=float)
    ynod = np.array([-dy / 2.0, -dy / 2.0, dy / 2.0, dy / 2.0], dtype=float)

    gp = 1.0 / np.sqrt(3.0)
    gauss_points = [(-gp, -gp), (gp, -gp), (gp, gp), (-gp, gp)]
    KE = np.zeros((8, 8), dtype=float)

    for xi, eta in gauss_points:
        dN_dxi = 0.25 * np.array([
            -(1.0 - eta),
             (1.0 - eta),
             (1.0 + eta),
            -(1.0 + eta),
        ], dtype=float)

        dN_deta = 0.25 * np.array([
            -(1.0 - xi),
            -(1.0 + xi),
             (1.0 + xi),
             (1.0 - xi),
        ], dtype=float)

        J = np.array([
            [np.dot(dN_dxi, xnod), np.dot(dN_deta, xnod)],
            [np.dot(dN_dxi, ynod), np.dot(dN_deta, ynod)],
        ], dtype=float)

        invJ = np.linalg.inv(J)
        dN = np.vstack((dN_dxi, dN_deta))
        dN_xy = invJ @ dN
        dN_dx = dN_xy[0, :]
        dN_dy = dN_xy[1, :]
        detJ = np.linalg.det(J)

        Bmat = np.zeros((3, 8), dtype=float)
        for a in range(4):
            Bmat[0, 2 * a] = dN_dx[a]
            Bmat[1, 2 * a + 1] = dN_dy[a]
            Bmat[2, 2 * a] = dN_dy[a]
            Bmat[2, 2 * a + 1] = dN_dx[a]

        KE += Bmat.T @ D @ Bmat * detJ

    return KE


def get_loads_and_bcs(nelx: int, nely: int, problem_name: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    ndof = 2 * (nelx + 1) * (nely + 1)
    F = np.zeros(ndof, dtype=float)

    if problem_name == "Tip_loaded_cantilever":
        load_node = node_id(nelx, nely, nelx)
        F[2 * load_node + 1] = -1.0

        fixed = []
        for iy in range(nely + 1):
            n = node_id(0, iy, nelx)
            fixed.extend([2 * n, 2 * n + 1])

    elif problem_name == "MBB":
        load_node = node_id(0, nely, nelx)
        F[2 * load_node + 1] = -1.0

        fixed = []
        for iy in range(nely + 1):
            n = node_id(0, iy, nelx)
            fixed.append(2 * n)

        bottom_right_node = node_id(nelx, 0, nelx)
        fixed.append(2 * bottom_right_node + 1)

    else:
        raise ValueError("Unknown problem_name. Use 'MBB' or 'Tip_loaded_cantilever'.")

    fixed = np.array(sorted(set(fixed)), dtype=int)
    free = np.setdiff1d(np.arange(ndof), fixed)
    return F, fixed, free


def build_problem_data(cfg: Config) -> Dict[str, Any]:
    nelx, nely = cfg.nelx, cfg.nely
    dx, dy = cfg.elem_size_x, cfg.elem_size_y
    nele = nelx * nely
    ndof = 2 * (nelx + 1) * (nely + 1)

    centers = np.zeros((nele, 2), dtype=float)
    elem_areas = np.full(nele, dx * dy, dtype=float)
    edofMat = np.zeros((nele, 8), dtype=int)

    e = 0
    for ey in range(nely):
        for ex in range(nelx):
            centers[e, :] = [(ex + 0.5) * dx, (ey + 0.5) * dy]

            n1 = node_id(ex, ey, nelx)
            n2 = node_id(ex + 1, ey, nelx)
            n3 = node_id(ex + 1, ey + 1, nelx)
            n4 = node_id(ex, ey + 1, nelx)

            edofMat[e, :] = [
                2 * n1, 2 * n1 + 1,
                2 * n2, 2 * n2 + 1,
                2 * n3, 2 * n3 + 1,
                2 * n4, 2 * n4 + 1,
            ]
            e += 1

    iK = np.kron(edofMat, np.ones((8, 1), dtype=int)).ravel()
    jK = np.kron(edofMat, np.ones((1, 8), dtype=int)).ravel()
    KE = q4_element_stiffness_rect(dx, dy, cfg.nu, cfg.plane_stress)
    F, fixed, free = get_loads_and_bcs(nelx, nely, cfg.problem_name)

    return {
        "centers": centers,
        "elem_areas": elem_areas,
        "edofMat": edofMat,
        "iK": iK,
        "jK": jK,
        "KE": KE,
        "F": F,
        "fixed": fixed,
        "free": free,
        "ndof": ndof,
        "nele": nele,
        "dx": dx,
        "dy": dy,
    }


# ============================================================
# FEA black box and training
# ============================================================

def fea_black_box(rho_torch: torch.Tensor, problem_data: Dict[str, Any], cfg: Config) -> Tuple[np.ndarray, float]:
    rho = rho_torch.detach().cpu().numpy().astype(float)
    rho = np.clip(rho, 1e-9, 1.0)

    E_e = cfg.Emin + (rho ** cfg.penal) * (cfg.E0 - cfg.Emin)
    sK = np.outer(E_e, problem_data["KE"].ravel()).ravel()

    K = sp.coo_matrix(
        (sK, (problem_data["iK"], problem_data["jK"])),
        shape=(problem_data["ndof"], problem_data["ndof"]),
    ).tocsc()
    K = 0.5 * (K + K.T)

    U = np.zeros(problem_data["ndof"], dtype=float)
    free = problem_data["free"]
    U[free] = spla.spsolve(K[free, :][:, free], problem_data["F"][free])

    Ue = U[problem_data["edofMat"]]
    Je0 = np.einsum("ij,ij->i", Ue @ problem_data["KE"], Ue)
    compliance = float(np.sum(E_e * Je0))
    return Je0, compliance


def compute_windowed_compliance_improvement(compliance_history: List[float], window: int) -> float:
    if len(compliance_history) < 2 * window:
        return np.inf
    older = np.mean(compliance_history[-2 * window:-window])
    recent = np.mean(compliance_history[-window:])
    return abs(recent - older) / max(abs(older), 1e-12)


def get_final_density(model: nn.Module, cfg: Config, problem_data: Dict[str, Any], device: torch.device) -> np.ndarray:
    coords = torch.tensor(problem_data["centers"], dtype=cfg.dtype, device=device)
    with torch.no_grad():
        model.eval()
        rho = model(coords).detach().cpu().numpy().reshape(cfg.nely, cfg.nelx)
    return rho


def train_one_case(cfg: Config) -> Tuple[nn.Module, Dict[str, List[float]], Dict[str, Any], torch.device]:
    torch.manual_seed(cfg.fourier_seed)
    np.random.seed(cfg.fourier_seed)

    device = resolve_device(cfg.device)
    problem_data = build_problem_data(cfg)

    coords = torch.tensor(problem_data["centers"], dtype=cfg.dtype, device=device)
    elem_areas = torch.tensor(problem_data["elem_areas"], dtype=cfg.dtype, device=device)

    V_total = float(problem_data["elem_areas"].sum())
    V_star_abs = cfg.volfrac * V_total

    model = FourierDensityNet(cfg).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg.lr)

    alm_lambda = float(cfg.alm_lambda0)
    alm_mu = float(cfg.alm_mu0)
    previous_rho = None
    patience_counter = 0
    J0 = None

    history: Dict[str, List[float]] = {
        "epoch": [],
        "compliance": [],
        "volfrac": [],
        "loss": [],
        "rho_change_max": [],
        "volfrac_residual": [],
        "compliance_rel_improve": [],
        "alm_lambda": [],
        "alm_mu": [],
    }

    print("\n" + "=" * 78)
    print(f"TONN-FFBD run | case = {cfg.problem_name} | VF = {cfg.volfrac}")
    print(f"Mesh                    : {cfg.nelx} x {cfg.nely}")
    print(f"Element size            : {cfg.elem_size_x:g} in x {cfg.elem_size_y:g} in")
    print(f"Physical domain         : {cfg.lx:g} in x {cfg.ly:g} in")
    print(f"Target min length       : {cfg.target_min_length:g} in")
    print(f"fmax                    : {cfg.fmax:g} cycles/in")
    print(f"Min Fourier wavelength  : {cfg.min_fourier_wavelength:g} in")
    print(f"Fourier features        : {cfg.num_fourier_features}")
    print("=" * 78)

    for epoch in range(cfg.max_epochs):
        model.train()
        optimizer.zero_grad()

        rho = model(coords).clamp(1e-6, 1.0 - 1e-6)
        Je0_np, compliance = fea_black_box(rho, problem_data, cfg)
        Je0 = torch.tensor(Je0_np, dtype=cfg.dtype, device=device)

        V_abs = torch.sum(rho * elem_areas)
        volfrac_current = V_abs / V_total
        g_v = (V_abs / V_star_abs) - 1.0
        volfrac_residual = volfrac_current / cfg.volfrac - 1.0

        if epoch == 0:
            J0 = max(float(compliance), 1e-12)

        loss = (compliance / J0) + alm_lambda * g_v + 0.5 * alm_mu * (g_v ** 2)

        dJ_drho = (
            -cfg.penal
            * (cfg.E0 - cfg.Emin)
            * torch.pow(rho.detach(), cfg.penal - 1.0)
            * Je0
            / J0
        )
        dg_drho = elem_areas / V_star_abs
        dL_drho = dJ_drho + (alm_lambda + alm_mu * g_v.detach()) * dg_drho

        rho.backward(dL_drho)
        optimizer.step()

        if (epoch + 1) % cfg.alm_update_every == 0:
            g_scalar = float(g_v.detach().cpu())
            alm_lambda = alm_lambda + alm_mu * g_scalar
            alm_mu = min(cfg.alm_mu_max, alm_mu * cfg.alm_mu_scale)

        rho_cpu = rho.detach().cpu().numpy()
        if previous_rho is None:
            rho_change_max = np.inf
        else:
            rho_change_max = float(np.max(np.abs(rho_cpu - previous_rho)))
        previous_rho = rho_cpu.copy()

        history["epoch"].append(epoch)
        history["compliance"].append(float(compliance))
        history["volfrac"].append(float(volfrac_current.detach().cpu()))
        history["loss"].append(float(loss.detach().cpu()))
        history["rho_change_max"].append(rho_change_max)
        history["volfrac_residual"].append(float(volfrac_residual.detach().cpu()))
        history["alm_lambda"].append(float(alm_lambda))
        history["alm_mu"].append(float(alm_mu))

        compliance_rel_improve = compute_windowed_compliance_improvement(
            history["compliance"], cfg.compliance_window
        )
        history["compliance_rel_improve"].append(compliance_rel_improve)

        enough_epochs = epoch >= cfg.min_epochs_before_stop
        volume_ok = abs(float(volfrac_residual.detach().cpu())) < cfg.volfrac_residual_tol
        rho_ok = rho_change_max < cfg.rho_change_max_tol
        compliance_ok = compliance_rel_improve < cfg.compliance_rel_improve_tol

        if enough_epochs and volume_ok or rho_ok and compliance_ok:
            patience_counter += 1
        else:
            patience_counter = 0

        if epoch % cfg.print_every == 0 or epoch == cfg.max_epochs - 1:
            improve_str = f"{compliance_rel_improve:9.3e}" if np.isfinite(compliance_rel_improve) else "      inf"
            print(
                f"iter={epoch:5d} | "
                f"loss={float(loss.detach().cpu()):11.5f} | "
                f"C={float(compliance):12.5f} | "
                f"VF={float(volfrac_current.detach().cpu()):8.5f} | "
                f"gVF={float(volfrac_residual.detach().cpu()):+9.5f} | "
                f"lam={alm_lambda:+10.3e} | "
                f"mu={alm_mu:10.3e} | "
                f"max|dRho|={rho_change_max:9.3e} | "
                f"rel dC={improve_str} | "
                f"pat={patience_counter}/{cfg.patience}"
            )

        if patience_counter >= cfg.patience:
            print(f"Converged at iteration {epoch}.")
            break

    return model, history, problem_data, device


# ============================================================
# Batch study and summary plotting
# ============================================================

def case_display_name(problem_name: str) -> str:
    if problem_name == "MBB":
        return "MBB"
    if problem_name == "Tip_loaded_cantilever":
        return "Tip-loaded Cantilever"
    return problem_name


def run_batch_study():
    problem_list = ["MBB", "Tip_loaded_cantilever"]
    volfrac_list = [0.2, 0.4, 0.6]

    base_cfg = Config()
    out_dir = Path(base_cfg.out_dir)
    if base_cfg.save_figures:
        out_dir.mkdir(parents=True, exist_ok=True)

    all_results: Dict[str, List[Dict[str, Any]]] = {p: [] for p in problem_list}

    for problem_name in problem_list:
        for vf in volfrac_list:
            cfg = Config(problem_name=problem_name, volfrac=vf)
            model, history, problem_data, device = train_one_case(cfg)
            rho = get_final_density(model, cfg, problem_data, device)

            final_compliance = history["compliance"][-1]
            final_vf = history["volfrac"][-1]
            final_epoch = history["epoch"][-1]

            all_results[problem_name].append({
                "cfg": cfg,
                "rho": rho,
                "history": history,
                "compliance": final_compliance,
                "volfrac_final": final_vf,
                "epoch": final_epoch,
            })

            del model
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            gc.collect()

    for problem_name in problem_list:
        display_name = case_display_name(problem_name)
        fig, axes = plt.subplots(3, 1, figsize=(9, 8), constrained_layout=True)

        for ax, result in zip(axes, all_results[problem_name]):
            cfg = result["cfg"]
            rho = result["rho"]
            ax.imshow(
                rho,
                cmap="gray_r",
                origin="lower",
                vmin=0.0,
                vmax=1.0,
                extent=[0, cfg.lx, 0, cfg.ly],
                aspect="equal",
                interpolation="nearest",
            )
            ax.set_axis_off()

            num_iter = result["epoch"] + 1

            ax.set_title(
                f"{display_name} | VF = {cfg.volfrac:.1f} | "
                f"C = {result['compliance']:.6g} | "
                f"VF_final = {result['volfrac_final']:.4f} | "
                f"Iterations = {num_iter}",
                fontsize=11,
                fontweight="normal",
            )
        fig.suptitle(
            f"TONN-FFBD Benchmark: {display_name} | "
            f"{base_cfg.nelx}x{base_cfg.nely} | Lmin = {base_cfg.target_min_length:g} in",
            fontsize=13,
            fontweight="bold",
        )

        if base_cfg.save_figures:
            safe_name = problem_name.lower()
            fig.savefig(out_dir / f"TONN_FFBD_{safe_name}_VF_study.png", dpi=300, bbox_inches="tight")

        plt.show()
        plt.close(fig)

    print("\n================ FINAL SUMMARY ================")
    for problem_name in problem_list:
        for result in all_results[problem_name]:
            cfg = result["cfg"]
            print(
                f"TONN-FFBD | {problem_name:24s} | "
                f"VF target = {cfg.volfrac:.2f} | "
                f"VF final = {result['volfrac_final']:.6f} | "
                f"C = {result['compliance']:.8g} | "
                f"epoch = {result['epoch']}"
            )
    print("================================================")

    if base_cfg.save_figures:
        print(f"\nSaved figures to:\n{out_dir.resolve()}")

    return all_results


if __name__ == "__main__":
    all_results = run_batch_study()