# -*- coding: utf-8 -*-
"""TONNFF_BD_LengthScale_Verification_study

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vhe1iXGWV8b8Gse90606Ad67q75CJOCq
"""

# ============================================================
# TONN-FF Bounded-Disk Length-Scale Factor Study
#
# Study:
#   fmax = 1 / (x * target_min_length)
#
# where:
#   x = 1, 2, 3, 4, 5, 6, 7, 8
#
# Problems:
#   1. Tip_loaded_cantilever
#   2. MBB
#
# Total cases:
#   8 x 2 = 16 cases
#
# Outputs:
#   - final coarse density for each case
#   - final high-resolution density for each case
#   - solid thickness violation map for each case
#   - critical circle overlay for each case
#   - thickness field for each case
#   - per-case summary txt
#   - global CSV summary
#   - violation fraction vs x plot
#   - minimum solid thickness vs x plot
#   - compliance vs x plot
# ============================================================

from dataclasses import dataclass, replace
from pathlib import Path
from typing import Optional, Dict, Any, List
import math
import sys
import gc
import csv

import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import scipy.ndimage as ndi
import matplotlib.pyplot as plt
from matplotlib.patches import Circle

import torch
import torch.nn as nn

try:
    from skimage.morphology import skeletonize
    SKIMAGE_AVAILABLE = True
except Exception:
    SKIMAGE_AVAILABLE = False
    skeletonize = None

try:
    from IPython.display import display
except Exception:
    display = None


# ============================================================
# Block 1 - Configuration
# ============================================================

@dataclass
class Config:
    # --------------------------------------------------------
    # Physical domain
    # --------------------------------------------------------
    nelx: int = 100
    nely: int = 50

    elem_size_x: float = 0.1
    elem_size_y: float = 0.1

    volfrac: float = 0.4
    problem_name: str = "Tip_loaded_cantilever"
    # Options:
    # "Tip_loaded_cantilever", "MBB"

    # --------------------------------------------------------
    # Material / FE
    # --------------------------------------------------------
    E0: float = 1.0
    Emin: float = 1e-9
    nu: float = 0.3
    plane_stress: bool = True
    penal: float = 3.0

    # --------------------------------------------------------
    # Bounded-disk Fourier feature settings
    # --------------------------------------------------------
    num_fourier_features: int = 512
    fourier_seed: int = 0

    # Physical target minimum feature size, inches
    target_min_length: float = 0.4

    # Study factor x in:
    #     fmax = 1 / (x * target_min_length)
    fmax_factor: int = 1

    # --------------------------------------------------------
    # Decoder MLP
    # --------------------------------------------------------
    num_hidden_layers: int = 4
    hidden_width: int = 256

    # --------------------------------------------------------
    # Optimizer
    # --------------------------------------------------------
    lr: float = 1e-3
    max_epochs: int = 1000

    # --------------------------------------------------------
    # One-sided ALM settings for V(rho) <= V0
    # --------------------------------------------------------
    alm_lambda0: float = 0.0
    alm_mu0: float = 5.0
    alm_update_every: int = 50
    alm_mu_scale: float = 1.2
    alm_mu_max: float = 50.0

    # --------------------------------------------------------
    # Stopping rule
    # --------------------------------------------------------
    rho_change_max_tol: float = 0.05
    volfrac_residual_tol: float = 0.001
    compliance_rel_improve_tol: float = 5e-3
    compliance_window: int = 10
    patience: int = 5
    min_epochs_before_stop: int = 100

    # --------------------------------------------------------
    # High-resolution reconstruction
    # --------------------------------------------------------
    samples_per_element: int = 15
    highres_batch_size: int = 200000

    # --------------------------------------------------------
    # Length-scale diagnostics
    # --------------------------------------------------------
    density_threshold: float = 0.5
    compute_void_thickness: bool = True
    min_component_area_pixels: int = 20

    # --------------------------------------------------------
    # Study output
    # --------------------------------------------------------
    out_dir: str = "/content/tounn_fmax_factor_study"
    save_outputs: bool = True

    # --------------------------------------------------------
    # Runtime
    # --------------------------------------------------------
    print_every: int = 25
    device: str = "auto"
    dtype: torch.dtype = torch.float32

    @property
    def lx(self) -> float:
        return self.nelx * self.elem_size_x

    @property
    def ly(self) -> float:
        return self.nely * self.elem_size_y

    @property
    def fmax(self) -> float:
        if self.target_min_length <= 0:
            raise ValueError("target_min_length must be positive.")
        if self.fmax_factor <= 0:
            raise ValueError("fmax_factor must be positive.")
        return 1.0 / (self.fmax_factor * self.target_min_length)

    @property
    def min_fourier_wavelength(self) -> float:
        return 1.0 / self.fmax

    @property
    def half_wavelength_estimate(self) -> float:
        return 0.5 * self.min_fourier_wavelength


# ============================================================
# Block 2 - Runtime helpers
# ============================================================

def resolve_device(device_string: str) -> torch.device:
    if device_string == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device_string == "cuda" and not torch.cuda.is_available():
        print("Requested CUDA, but no GPU is available. Falling back to CPU.")
        return torch.device("cpu")
    return torch.device(device_string)


def clean_cuda_memory():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def safe_logit(p: float, eps: float = 1e-6) -> float:
    p = float(np.clip(p, eps, 1.0 - eps))
    return math.log(p / (1.0 - p))


def make_problem_tag(problem_name: str) -> str:
    if problem_name == "Tip_loaded_cantilever":
        return "Tip_loaded_Cantilever"
    if problem_name == "MBB":
        return "MBB"
    return problem_name.strip().replace(" ", "_")


def make_run_tag(cfg: Config) -> str:
    problem_tag = make_problem_tag(cfg.problem_name)
    ff_tag = f"x{cfg.fmax_factor}_Fmax{cfg.fmax:g}_Lmin{cfg.target_min_length:g}"
    mesh_tag = f"TM{cfg.nelx}X{cfg.nely}"
    elem_tag = f"Elem{cfg.elem_size_x:g}X{cfg.elem_size_y:g}"
    vf_tag = f"VF{cfg.volfrac:g}"
    seed_tag = f"Seed{cfg.fourier_seed}"

    return f"{problem_tag}_{ff_tag}_{mesh_tag}_{elem_tag}_{vf_tag}_{seed_tag}"


# ============================================================
# Block 3 - Bounded Disk Fourier Feature Map
# ============================================================

class BoundedDiskFourierFeatureMap(nn.Module):
    def __init__(
        self,
        in_dim: int,
        num_fourier_features: int,
        fmax: float,
        seed: int = 0,
    ):
        super().__init__()

        if in_dim != 2:
            raise ValueError("This Fourier map assumes 2D coordinates.")
        if fmax <= 0:
            raise ValueError("fmax must be positive.")

        gen = torch.Generator(device="cpu")
        gen.manual_seed(seed)

        theta = 2.0 * math.pi * torch.rand(num_fourier_features, generator=gen)
        r = fmax * torch.rand(num_fourier_features, generator=gen)

        bx = r * torch.cos(theta)
        by = r * torch.sin(theta)

        B = torch.stack([bx, by], dim=1)

        self.fmax = fmax
        self.register_buffer("B", B)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        xb = 2.0 * math.pi * (x @ self.B.T)
        return torch.cat([torch.cos(xb), torch.sin(xb)], dim=1)


# ============================================================
# Block 4 - Mesh, BCs, and Q4 FE helpers
# ============================================================

def node_id(ix, iy, nelx):
    return iy * (nelx + 1) + ix


def q4_element_stiffness_rect(dx, dy, nu, plane_stress=True):
    if plane_stress:
        D = (1.0 / (1.0 - nu**2)) * np.array([
            [1.0, nu, 0.0],
            [nu, 1.0, 0.0],
            [0.0, 0.0, (1.0 - nu) / 2.0],
        ], dtype=float)
    else:
        D = ((1.0 - nu) / ((1.0 + nu) * (1.0 - 2.0 * nu))) * np.array([
            [1.0, nu / (1.0 - nu), 0.0],
            [nu / (1.0 - nu), 1.0, 0.0],
            [0.0, 0.0, (1.0 - 2.0 * nu) / (2.0 * (1.0 - nu))],
        ], dtype=float)

    xnod = np.array([-dx / 2, dx / 2, dx / 2, -dx / 2], dtype=float)
    ynod = np.array([-dy / 2, -dy / 2, dy / 2, dy / 2], dtype=float)

    gp = 1.0 / np.sqrt(3.0)
    gauss_points = [(-gp, -gp), (gp, -gp), (gp, gp), (-gp, gp)]
    KE = np.zeros((8, 8), dtype=float)

    for xi, eta in gauss_points:
        dN_dxi = 0.25 * np.array([
            -(1.0 - eta),
             (1.0 - eta),
             (1.0 + eta),
            -(1.0 + eta),
        ], dtype=float)

        dN_deta = 0.25 * np.array([
            -(1.0 - xi),
            -(1.0 + xi),
             (1.0 + xi),
             (1.0 - xi),
        ], dtype=float)

        J = np.array([
            [np.dot(dN_dxi, xnod), np.dot(dN_deta, xnod)],
            [np.dot(dN_dxi, ynod), np.dot(dN_deta, ynod)],
        ], dtype=float)

        invJ = np.linalg.inv(J)
        dN = np.vstack((dN_dxi, dN_deta))
        dN_xy = invJ @ dN

        dN_dx = dN_xy[0, :]
        dN_dy = dN_xy[1, :]
        detJ = np.linalg.det(J)

        Bmat = np.zeros((3, 8), dtype=float)
        for a in range(4):
            Bmat[0, 2 * a] = dN_dx[a]
            Bmat[1, 2 * a + 1] = dN_dy[a]
            Bmat[2, 2 * a] = dN_dy[a]
            Bmat[2, 2 * a + 1] = dN_dx[a]

        KE += Bmat.T @ D @ Bmat * detJ

    return KE


def get_loads_and_bcs(nelx, nely, problem_name):
    ndof = 2 * (nelx + 1) * (nely + 1)
    F = np.zeros(ndof, dtype=float)

    if problem_name == "Tip_loaded_cantilever":
        load_node = node_id(nelx, nely, nelx)
        F[2 * load_node + 1] = -1.0

        fixed = []
        for iy in range(nely + 1):
            n = node_id(0, iy, nelx)
            fixed.extend([2 * n, 2 * n + 1])

    elif problem_name == "MBB":
        load_node = node_id(0, nely, nelx)
        F[2 * load_node + 1] = -1.0

        fixed = []
        for iy in range(nely + 1):
            n = node_id(0, iy, nelx)
            fixed.append(2 * n)

        br = node_id(nelx, 0, nelx)
        fixed.append(2 * br + 1)

    else:
        raise ValueError("Unknown problem_name.")

    fixed = np.array(sorted(set(fixed)), dtype=int)
    free = np.setdiff1d(np.arange(ndof), fixed)

    return F, fixed, free


def build_problem_data(cfg):
    nelx, nely = cfg.nelx, cfg.nely
    dx = cfg.elem_size_x
    dy = cfg.elem_size_y

    nele = nelx * nely
    ndof = 2 * (nelx + 1) * (nely + 1)

    centers = np.zeros((nele, 2), dtype=float)
    elem_areas = np.full(nele, dx * dy, dtype=float)
    edofMat = np.zeros((nele, 8), dtype=int)

    e = 0
    for ey in range(nely):
        for ex in range(nelx):
            centers[e, :] = [
                (ex + 0.5) * dx,
                (ey + 0.5) * dy,
            ]

            n1 = node_id(ex, ey, nelx)
            n2 = node_id(ex + 1, ey, nelx)
            n3 = node_id(ex + 1, ey + 1, nelx)
            n4 = node_id(ex, ey + 1, nelx)

            edofMat[e, :] = [
                2 * n1, 2 * n1 + 1,
                2 * n2, 2 * n2 + 1,
                2 * n3, 2 * n3 + 1,
                2 * n4, 2 * n4 + 1,
            ]

            e += 1

    iK = np.kron(edofMat, np.ones((8, 1), dtype=int)).ravel()
    jK = np.kron(edofMat, np.ones((1, 8), dtype=int)).ravel()

    KE = q4_element_stiffness_rect(dx, dy, cfg.nu, cfg.plane_stress)
    F, fixed, free = get_loads_and_bcs(nelx, nely, cfg.problem_name)

    return {
        "centers": centers,
        "elem_areas": elem_areas,
        "edofMat": edofMat,
        "iK": iK,
        "jK": jK,
        "KE": KE,
        "F": F,
        "fixed": fixed,
        "free": free,
        "ndof": ndof,
        "nele": nele,
        "dx": dx,
        "dy": dy,
    }


# ============================================================
# Block 5 - FEA black box
# ============================================================

def fea_black_box(rho_torch, problem_data, cfg):
    rho = rho_torch.detach().cpu().numpy().astype(float)
    rho = np.clip(rho, 1e-9, 1.0)

    E_e = cfg.Emin + (rho ** cfg.penal) * (cfg.E0 - cfg.Emin)
    sK = np.outer(E_e, problem_data["KE"].ravel()).ravel()

    K = sp.coo_matrix(
        (sK, (problem_data["iK"], problem_data["jK"])),
        shape=(problem_data["ndof"], problem_data["ndof"]),
    ).tocsc()

    K = 0.5 * (K + K.T)

    U = np.zeros(problem_data["ndof"], dtype=float)
    free = problem_data["free"]

    U[free] = spla.spsolve(K[free, :][:, free], problem_data["F"][free])

    Ue = U[problem_data["edofMat"]]
    Je0 = np.einsum("ij,ij->i", Ue @ problem_data["KE"], Ue)

    compliance = np.sum(E_e * Je0)

    return Je0, float(compliance)


def compute_windowed_compliance_improvement(compliance_history, window):
    if len(compliance_history) < 2 * window:
        return np.inf

    older = np.mean(compliance_history[-2 * window:-window])
    recent = np.mean(compliance_history[-window:])

    return abs(recent - older) / max(abs(older), 1e-12)


# ============================================================
# Block 6 - Fourier density network
# ============================================================

class FourierDensityNet(nn.Module):
    def __init__(self, cfg: Config):
        super().__init__()

        self.fourier = BoundedDiskFourierFeatureMap(
            in_dim=2,
            num_fourier_features=cfg.num_fourier_features,
            fmax=cfg.fmax,
            seed=cfg.fourier_seed,
        )

        input_dim = 2 * cfg.num_fourier_features
        in_dim = input_dim

        self.hidden_linears = nn.ModuleList()

        for _ in range(cfg.num_hidden_layers):
            layer = nn.Linear(in_dim, cfg.hidden_width)
            self.hidden_linears.append(layer)
            in_dim = cfg.hidden_width

        self.out = nn.Linear(in_dim, 1)
        self.activation = nn.LeakyReLU(negative_slope=0.01)

        self.reset_parameters(cfg.volfrac)

    def reset_parameters(self, volfrac: float):
        for layer in self.hidden_linears:
            nn.init.orthogonal_(layer.weight)
            nn.init.zeros_(layer.bias)

        nn.init.normal_(self.out.weight, mean=0.0, std=1e-4)
        nn.init.constant_(self.out.bias, safe_logit(volfrac))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        z = self.fourier(x)

        h = z
        for layer in self.hidden_linears:
            h = self.activation(layer(h))

        logits = self.out(h)
        rho = torch.sigmoid(logits).squeeze(1)

        return rho


# ============================================================
# Block 7 - High-resolution sampling
# ============================================================

def sample_highres_density(model, cfg, device):
    s = cfg.samples_per_element

    nx_hr = cfg.nelx * s
    ny_hr = cfg.nely * s

    dx_hr = cfg.lx / nx_hr
    dy_hr = cfg.ly / ny_hr

    xs = (np.arange(nx_hr) + 0.5) * dx_hr
    ys = (np.arange(ny_hr) + 0.5) * dy_hr

    XX, YY = np.meshgrid(xs, ys)
    pts = np.column_stack([XX.ravel(), YY.ravel()])

    rho_chunks = []

    with torch.no_grad():
        model.eval()

        for i in range(0, pts.shape[0], cfg.highres_batch_size):
            batch = pts[i:i + cfg.highres_batch_size]
            pts_t = torch.tensor(batch, dtype=cfg.dtype, device=device)
            rho_batch = model(pts_t).detach().cpu().numpy()
            rho_chunks.append(rho_batch)

    rho_hr = np.concatenate(rho_chunks).reshape(ny_hr, nx_hr)

    return rho_hr


def get_final_density(model, cfg, problem_data, device):
    coords = torch.tensor(problem_data["centers"], dtype=cfg.dtype, device=device)

    with torch.no_grad():
        model.eval()
        rho = model(coords).detach().cpu().numpy().reshape(cfg.nely, cfg.nelx)

    return rho


# ============================================================
# Block 8 - Length-scale diagnostics
# ============================================================

def remove_small_components(mask: np.ndarray, min_area_pixels: int) -> np.ndarray:
    if min_area_pixels <= 0:
        return mask.astype(bool)

    labels, nlab = ndi.label(mask)

    if nlab == 0:
        return mask.astype(bool)

    counts = np.bincount(labels.ravel())
    keep = np.zeros_like(counts, dtype=bool)
    keep[counts >= min_area_pixels] = True
    keep[0] = False

    return keep[labels]


def compute_skeleton(mask: np.ndarray) -> np.ndarray:
    mask = mask.astype(bool)

    if SKIMAGE_AVAILABLE:
        return skeletonize(mask)

    dist = ndi.distance_transform_edt(mask)
    local_max = dist == ndi.maximum_filter(dist, size=3)

    return local_max & mask


def analyze_region_thickness(
    region_mask: np.ndarray,
    dx: float,
    dy: float,
    target_min_length: float,
    min_component_area_pixels: int = 20,
) -> Dict[str, Any]:

    region_mask = region_mask.astype(bool)
    region_mask = remove_small_components(region_mask, min_component_area_pixels)

    if np.sum(region_mask) == 0:
        return {
            "valid": False,
            "message": "Region mask is empty.",
        }

    dist = ndi.distance_transform_edt(region_mask, sampling=(dy, dx))
    skel = compute_skeleton(region_mask)
    valid_skel = skel & (dist > 0.0)

    if np.sum(valid_skel) == 0:
        return {
            "valid": False,
            "message": "Skeleton is empty.",
            "distance": dist,
            "skeleton": skel,
        }

    thickness = 2.0 * dist

    skel_values = thickness[valid_skel]
    candidate_indices = np.flatnonzero(valid_skel)

    min_local_index = int(np.argmin(skel_values))
    min_flat_index = int(candidate_indices[min_local_index])
    row, col = np.unravel_index(min_flat_index, region_mask.shape)

    min_thickness = float(thickness[row, col])
    local_radius = float(dist[row, col])

    violation_mask = valid_skel & (thickness < target_min_length)
    violation_fraction = float(np.sum(violation_mask) / max(np.sum(valid_skel), 1))

    return {
        "valid": True,
        "distance": dist,
        "thickness": thickness,
        "skeleton": skel,
        "valid_skeleton": valid_skel,
        "violation_mask": violation_mask,
        "min_thickness": min_thickness,
        "critical_row": int(row),
        "critical_col": int(col),
        "critical_radius": local_radius,
        "violation_fraction": violation_fraction,
        "num_skeleton_pixels": int(np.sum(valid_skel)),
    }


def analyze_lengthscale(rho_hr: np.ndarray, cfg: Config) -> Dict[str, Any]:
    ny_hr, nx_hr = rho_hr.shape

    dx_hr = cfg.lx / nx_hr
    dy_hr = cfg.ly / ny_hr

    solid_mask = rho_hr >= cfg.density_threshold
    void_mask = ~solid_mask

    solid_result = analyze_region_thickness(
        region_mask=solid_mask,
        dx=dx_hr,
        dy=dy_hr,
        target_min_length=cfg.target_min_length,
        min_component_area_pixels=cfg.min_component_area_pixels,
    )

    if cfg.compute_void_thickness:
        void_result = analyze_region_thickness(
            region_mask=void_mask,
            dx=dx_hr,
            dy=dy_hr,
            target_min_length=cfg.target_min_length,
            min_component_area_pixels=cfg.min_component_area_pixels,
        )
    else:
        void_result = {
            "valid": False,
            "message": "Void thickness not requested.",
        }

    return {
        "dx_hr": dx_hr,
        "dy_hr": dy_hr,
        "solid_mask": solid_mask,
        "void_mask": void_mask,
        "solid": solid_result,
        "void": void_result,
    }


def pixel_to_physical(row: int, col: int, cfg: Config, rho_hr: np.ndarray):
    ny_hr, nx_hr = rho_hr.shape
    dx_hr = cfg.lx / nx_hr
    dy_hr = cfg.ly / ny_hr

    x = (col + 0.5) * dx_hr
    y = (row + 0.5) * dy_hr

    return x, y


# ============================================================
# Block 9 - Plotting
# ============================================================

def plot_topology_with_critical_circle(
    rho_hr: np.ndarray,
    length_result: Dict[str, Any],
    cfg: Config,
    out_path: Optional[Path] = None,
):
    solid = length_result["solid"]

    fig, ax = plt.subplots(figsize=(10, 5))

    ax.imshow(
        rho_hr,
        cmap="gray_r",
        origin="lower",
        vmin=0.0,
        vmax=1.0,
        extent=[0, cfg.lx, 0, cfg.ly],
        aspect="equal",
        interpolation="nearest",
    )

    ax.set_xlabel("x [in]")
    ax.set_ylabel("y [in]")

    title = (
        f"{cfg.problem_name} | x = {cfg.fmax_factor} | "
        f"fmax = {cfg.fmax:.4g} cycles/in\n"
        f"Target Lmin = {cfg.target_min_length:g} in"
    )

    if solid.get("valid", False):
        row = solid["critical_row"]
        col = solid["critical_col"]
        xcrit, ycrit = pixel_to_physical(row, col, cfg, rho_hr)

        target_radius = cfg.target_min_length / 2.0
        measured_radius = solid["critical_radius"]

        ax.add_patch(
            Circle(
                (xcrit, ycrit),
                target_radius,
                fill=False,
                linewidth=2.0,
                edgecolor="red",
                label=f"Target diameter = {cfg.target_min_length:g} in",
            )
        )

        ax.add_patch(
            Circle(
                (xcrit, ycrit),
                measured_radius,
                fill=False,
                linewidth=1.5,
                linestyle="--",
                edgecolor="blue",
                label=f"Measured diameter = {solid['min_thickness']:.4g} in",
            )
        )

        ax.plot(xcrit, ycrit, marker="x", markersize=8, color="red")
        title += f"\nMin solid thickness = {solid['min_thickness']:.4g} in"
        ax.legend(loc="upper right")

    ax.set_title(title)
    plt.tight_layout()

    if out_path is not None:
        fig.savefig(out_path, dpi=300, bbox_inches="tight")

    plt.close(fig)


def plot_thickness_violation_map(
    rho_hr: np.ndarray,
    length_result: Dict[str, Any],
    cfg: Config,
    out_path: Optional[Path] = None,
):
    solid = length_result["solid"]

    fig, ax = plt.subplots(figsize=(10, 5))

    ax.imshow(
        rho_hr,
        cmap="gray_r",
        origin="lower",
        vmin=0.0,
        vmax=1.0,
        extent=[0, cfg.lx, 0, cfg.ly],
        aspect="equal",
        interpolation="nearest",
    )

    vf = np.nan

    if solid.get("valid", False):
        violation = solid["violation_mask"]
        yy, xx = np.where(violation)
        vf = solid["violation_fraction"]

        if len(xx) > 0:
            dx_hr = length_result["dx_hr"]
            dy_hr = length_result["dy_hr"]

            x_phys = (xx + 0.5) * dx_hr
            y_phys = (yy + 0.5) * dy_hr

            ax.scatter(
                x_phys,
                y_phys,
                s=4,
                c="red",
                label=f"solid skeleton thickness < {cfg.target_min_length:g} in",
            )
            ax.legend(loc="upper right")

        title = (
            f"{cfg.problem_name} | x = {cfg.fmax_factor} | "
            f"fmax = {cfg.fmax:.4g} cycles/in\n"
            f"Solid violation fraction = {vf:.4g}"
        )
    else:
        title = f"{cfg.problem_name} | x = {cfg.fmax_factor} | violation map unavailable"

    ax.set_xlabel("x [in]")
    ax.set_ylabel("y [in]")
    ax.set_title(title)

    plt.tight_layout()

    if out_path is not None:
        fig.savefig(out_path, dpi=300, bbox_inches="tight")

    plt.close(fig)


def plot_thickness_field(
    length_result: Dict[str, Any],
    cfg: Config,
    out_path: Optional[Path] = None,
):
    solid = length_result["solid"]

    if not solid.get("valid", False):
        return

    thickness = solid["thickness"].copy()
    solid_mask = length_result["solid_mask"]
    thickness[~solid_mask] = np.nan

    fig, ax = plt.subplots(figsize=(10, 5))

    im = ax.imshow(
        thickness,
        origin="lower",
        extent=[0, cfg.lx, 0, cfg.ly],
        aspect="equal",
        interpolation="nearest",
    )

    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label("Local solid thickness [in]")

    ax.contour(
        thickness,
        levels=[cfg.target_min_length],
        origin="lower",
        extent=[0, cfg.lx, 0, cfg.ly],
        linewidths=1.5,
        colors="red",
    )

    ax.set_xlabel("x [in]")
    ax.set_ylabel("y [in]")
    ax.set_title(
        f"{cfg.problem_name} | x = {cfg.fmax_factor} | "
        f"local solid thickness\n"
        f"Red contour = target Lmin {cfg.target_min_length:g} in"
    )

    plt.tight_layout()

    if out_path is not None:
        fig.savefig(out_path, dpi=300, bbox_inches="tight")

    plt.close(fig)


def plot_density(
    rho: np.ndarray,
    cfg: Config,
    out_path: Optional[Path] = None,
    highres: bool = False,
):
    fig, ax = plt.subplots(figsize=(10, 5))

    ax.imshow(
        rho,
        cmap="gray_r",
        origin="lower",
        vmin=0.0,
        vmax=1.0,
        extent=[0, cfg.lx, 0, cfg.ly],
        aspect="equal",
        interpolation="nearest" if highres else None,
    )

    ax.set_xlabel("x [in]")
    ax.set_ylabel("y [in]")

    res = "High-resolution" if highres else "Coarse"
    ax.set_title(
        f"{res} density | {cfg.problem_name} | x = {cfg.fmax_factor}\n"
        f"fmax = {cfg.fmax:.4g} cycles/in | Lmin target = {cfg.target_min_length:g} in"
    )

    plt.tight_layout()

    if out_path is not None:
        fig.savefig(out_path, dpi=300, bbox_inches="tight")

    plt.close(fig)


# ============================================================
# Block 10 - Training
# ============================================================

def train(cfg: Config):
    device = resolve_device(cfg.device)
    problem_data = build_problem_data(cfg)

    coords = torch.tensor(problem_data["centers"], dtype=cfg.dtype, device=device)
    elem_areas = torch.tensor(problem_data["elem_areas"], dtype=cfg.dtype, device=device)

    V_total = float(problem_data["elem_areas"].sum())
    V_star_abs = cfg.volfrac * V_total

    model = FourierDensityNet(cfg).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg.lr)

    previous_rho = None
    patience_counter = 0

    alm_lambda = float(cfg.alm_lambda0)
    alm_mu = float(cfg.alm_mu0)
    prev_g_plus_for_mu = None

    J0 = None

    history = {
        "epoch": [],
        "compliance": [],
        "volfrac": [],
        "loss": [],
        "rho_change_max": [],
        "volfrac_residual": [],
        "compliance_rel_improve": [],
        "patience_counter": [],
        "alm_lambda": [],
        "alm_mu": [],
        "g_plus": [],
    }

    print("=" * 92)
    print(f"Case: problem={cfg.problem_name} | x={cfg.fmax_factor} | fmax={cfg.fmax:.6g}")
    print(f"Target Lmin={cfg.target_min_length:.6g} in | min Fourier wavelength={cfg.min_fourier_wavelength:.6g} in")
    print(f"Mesh={cfg.nelx}x{cfg.nely} | domain={cfg.lx:g}x{cfg.ly:g} in | device={device}")
    print("=" * 92)

    for epoch in range(cfg.max_epochs):
        model.train()
        optimizer.zero_grad()

        rho = model(coords).clamp(1e-6, 1.0 - 1e-6)

        Je0_np, compliance = fea_black_box(rho, problem_data, cfg)
        Je0 = torch.tensor(Je0_np, dtype=cfg.dtype, device=device)

        V_abs = torch.sum(rho * elem_areas)
        volfrac_current = V_abs / V_total
        volfrac_residual = volfrac_current / cfg.volfrac - 1.0

        g_v = (V_abs / V_star_abs) - 1.0
        g_plus = torch.clamp(g_v, min=0.0)

        if epoch == 0:
            J0 = max(float(compliance), 1e-12)

        loss = (compliance / J0) + alm_lambda * g_plus + 0.5 * alm_mu * (g_plus ** 2)

        dJ_drho = (
            -cfg.penal
            * (cfg.E0 - cfg.Emin)
            * torch.pow(rho.detach(), cfg.penal - 1.0)
            * Je0
            / J0
        )

        dVabs_drho = elem_areas
        dg_drho = dVabs_drho / V_star_abs
        active_mask = (g_v.detach() > 0.0).to(cfg.dtype)

        dL_drho = dJ_drho + (
            alm_lambda + alm_mu * g_plus.detach()
        ) * active_mask * dg_drho

        rho.backward(dL_drho)
        optimizer.step()

        if (epoch + 1) % cfg.alm_update_every == 0:
            g_scalar = float(g_v.detach().cpu())
            g_plus_scalar = max(g_scalar, 0.0)

            alm_lambda = max(0.0, alm_lambda + alm_mu * g_scalar)

            if prev_g_plus_for_mu is not None and g_plus_scalar > 0.25 * prev_g_plus_for_mu:
                alm_mu = min(cfg.alm_mu_max, alm_mu * cfg.alm_mu_scale)

            prev_g_plus_for_mu = g_plus_scalar

        rho_cpu = rho.detach().cpu().numpy()

        if previous_rho is None:
            rho_change_max = np.inf
        else:
            rho_change_max = float(np.max(np.abs(rho_cpu - previous_rho)))

        previous_rho = rho_cpu.copy()

        history["epoch"].append(epoch)
        history["compliance"].append(float(compliance))
        history["volfrac"].append(float(volfrac_current.detach().cpu()))
        history["loss"].append(float(loss.detach().cpu()))
        history["rho_change_max"].append(rho_change_max)
        history["volfrac_residual"].append(float(volfrac_residual.detach().cpu()))
        history["alm_lambda"].append(float(alm_lambda))
        history["alm_mu"].append(float(alm_mu))
        history["g_plus"].append(float(g_plus.detach().cpu()))

        compliance_rel_improve = compute_windowed_compliance_improvement(
            history["compliance"],
            cfg.compliance_window,
        )
        history["compliance_rel_improve"].append(compliance_rel_improve)

        enough_epochs = epoch >= cfg.min_epochs_before_stop
        volume_ok = abs(float(volfrac_residual.detach().cpu())) < cfg.volfrac_residual_tol
        rho_ok = rho_change_max < cfg.rho_change_max_tol
        compliance_ok = compliance_rel_improve < cfg.compliance_rel_improve_tol

        if enough_epochs and volume_ok or rho_ok and compliance_ok:
            patience_counter += 1
        else:
            patience_counter = 0

        history["patience_counter"].append(patience_counter)

        if epoch % cfg.print_every == 0 or epoch == cfg.max_epochs - 1:
            improve_str = (
                f"{compliance_rel_improve:9.3e}"
                if np.isfinite(compliance_rel_improve)
                else "      inf"
            )

            print(
                f"iter={epoch:5d} | "
                f"J={float(compliance):12.5f} | "
                f"VF={float(volfrac_current.detach().cpu()):7.4f} | "
                f"gVF={float(volfrac_residual.detach().cpu()):+9.5f} | "
                f"max|dRho|={rho_change_max:9.3e} | "
                f"rel dC={improve_str} | "
                f"pat={patience_counter:3d}/{cfg.patience:3d}"
            )

        if patience_counter >= cfg.patience:
            print(f"Converged at iteration {epoch}.")
            break

    return model, history, problem_data, device


# ============================================================
# Block 11 - One case runner
# ============================================================

def run_one_case(cfg: Config) -> Dict[str, Any]:
    run_tag = make_run_tag(cfg)
    case_dir = Path(cfg.out_dir) / make_problem_tag(cfg.problem_name) / f"x_{cfg.fmax_factor}"
    case_dir.mkdir(parents=True, exist_ok=True)

    model, history, problem_data, device = train(cfg)

    rho_coarse = get_final_density(model, cfg, problem_data, device)
    rho_hr = sample_highres_density(model, cfg, device)
    length_result = analyze_lengthscale(rho_hr, cfg)

    final_compliance = float(history["compliance"][-1])
    final_volfrac = float(history["volfrac"][-1])
    final_epoch = int(history["epoch"][-1])

    solid = length_result["solid"]
    void = length_result["void"]

    solid_violation_fraction = np.nan
    solid_min_thickness = np.nan
    void_violation_fraction = np.nan
    void_min_thickness = np.nan

    if solid.get("valid", False):
        solid_violation_fraction = float(solid["violation_fraction"])
        solid_min_thickness = float(solid["min_thickness"])

    if void.get("valid", False):
        void_violation_fraction = float(void["violation_fraction"])
        void_min_thickness = float(void["min_thickness"])

    plot_density(
        rho_coarse,
        cfg,
        out_path=case_dir / f"{run_tag}_coarse_density.png",
        highres=False,
    )

    plot_density(
        rho_hr,
        cfg,
        out_path=case_dir / f"{run_tag}_highres_density.png",
        highres=True,
    )

    plot_thickness_violation_map(
        rho_hr,
        length_result,
        cfg,
        out_path=case_dir / f"{run_tag}_solid_violation_map.png",
    )

    plot_topology_with_critical_circle(
        rho_hr,
        length_result,
        cfg,
        out_path=case_dir / f"{run_tag}_critical_circle.png",
    )

    plot_thickness_field(
        length_result,
        cfg,
        out_path=case_dir / f"{run_tag}_solid_thickness_field.png",
    )

    summary_path = case_dir / f"{run_tag}_summary.txt"
    with open(summary_path, "w") as f:
        f.write("TONN-FF length-scale factor study case summary\n")
        f.write("=" * 70 + "\n")
        f.write(f"problem_name                 : {cfg.problem_name}\n")
        f.write(f"fmax_factor_x                : {cfg.fmax_factor}\n")
        f.write(f"target_min_length            : {cfg.target_min_length}\n")
        f.write(f"fmax                         : {cfg.fmax}\n")
        f.write(f"min_fourier_wavelength       : {cfg.min_fourier_wavelength}\n")
        f.write(f"half_wavelength_estimate     : {cfg.half_wavelength_estimate}\n")
        f.write(f"final_compliance             : {final_compliance}\n")
        f.write(f"final_volfrac                : {final_volfrac}\n")
        f.write(f"final_epoch                  : {final_epoch}\n")
        f.write(f"solid_min_thickness          : {solid_min_thickness}\n")
        f.write(f"solid_violation_fraction     : {solid_violation_fraction}\n")
        f.write(f"void_min_thickness           : {void_min_thickness}\n")
        f.write(f"void_violation_fraction      : {void_violation_fraction}\n")
        f.write(f"density_threshold            : {cfg.density_threshold}\n")

    result = {
        "problem_name": cfg.problem_name,
        "fmax_factor_x": cfg.fmax_factor,
        "target_min_length": cfg.target_min_length,
        "fmax": cfg.fmax,
        "min_fourier_wavelength": cfg.min_fourier_wavelength,
        "half_wavelength_estimate": cfg.half_wavelength_estimate,
        "final_compliance": final_compliance,
        "final_volfrac": final_volfrac,
        "final_epoch": final_epoch,
        "solid_min_thickness": solid_min_thickness,
        "solid_violation_fraction": solid_violation_fraction,
        "void_min_thickness": void_min_thickness,
        "void_violation_fraction": void_violation_fraction,
        "case_dir": str(case_dir),
    }

    del model
    clean_cuda_memory()

    return result


# ============================================================
# Block 12 - Study summary plotting
# ============================================================

def save_study_csv(results: List[Dict[str, Any]], out_dir: Path):
    csv_path = out_dir / "fmax_factor_study_summary.csv"

    fieldnames = [
        "problem_name",
        "fmax_factor_x",
        "target_min_length",
        "fmax",
        "min_fourier_wavelength",
        "half_wavelength_estimate",
        "final_compliance",
        "final_volfrac",
        "final_epoch",
        "solid_min_thickness",
        "solid_violation_fraction",
        "void_min_thickness",
        "void_violation_fraction",
        "case_dir",
    ]

    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in results:
            writer.writerow(row)

    print(f"Saved study CSV: {csv_path}")


def plot_metric_vs_factor(
    results: List[Dict[str, Any]],
    metric_key: str,
    ylabel: str,
    title: str,
    out_path: Path,
):
    fig, ax = plt.subplots(figsize=(8, 5))

    problems = sorted(set(r["problem_name"] for r in results))

    for problem in problems:
        rows = [r for r in results if r["problem_name"] == problem]
        rows = sorted(rows, key=lambda r: r["fmax_factor_x"])

        xs = [r["fmax_factor_x"] for r in rows]
        ys = [r[metric_key] for r in rows]

        ax.plot(xs, ys, marker="o", label=problem)

    ax.set_xlabel(r"factor $x$ in $f_{\max}=1/(x\ell_{\min})$")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.grid(True, alpha=0.3)
    ax.legend()

    plt.tight_layout()
    fig.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close(fig)


def make_study_summary_plots(results: List[Dict[str, Any]], out_dir: Path):
    plot_metric_vs_factor(
        results=results,
        metric_key="solid_violation_fraction",
        ylabel="Solid violation fraction",
        title="Solid length-scale violation fraction vs Fourier cutoff factor",
        out_path=out_dir / "summary_solid_violation_fraction_vs_x.png",
    )

    plot_metric_vs_factor(
        results=results,
        metric_key="solid_min_thickness",
        ylabel="Minimum measured solid thickness [in]",
        title="Minimum measured solid thickness vs Fourier cutoff factor",
        out_path=out_dir / "summary_solid_min_thickness_vs_x.png",
    )

    plot_metric_vs_factor(
        results=results,
        metric_key="final_compliance",
        ylabel="Final compliance",
        title="Final compliance vs Fourier cutoff factor",
        out_path=out_dir / "summary_compliance_vs_x.png",
    )

    plot_metric_vs_factor(
        results=results,
        metric_key="final_volfrac",
        ylabel="Final volume fraction",
        title="Final volume fraction vs Fourier cutoff factor",
        out_path=out_dir / "summary_volfrac_vs_x.png",
    )

    if any(np.isfinite(r["void_violation_fraction"]) for r in results):
        plot_metric_vs_factor(
            results=results,
            metric_key="void_violation_fraction",
            ylabel="Void violation fraction",
            title="Void length-scale violation fraction vs Fourier cutoff factor",
            out_path=out_dir / "summary_void_violation_fraction_vs_x.png",
        )


# ============================================================
# Block 13 - Study driver
# ============================================================

def run_fmax_factor_study():
    base_cfg = Config()

    out_dir = Path(base_cfg.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    problems = [
        "Tip_loaded_cantilever",
        "MBB",
    ]

    x_values = list(range(1, 9))

    results = []

    print("\n" + "=" * 100)
    print("STARTING FMAX FACTOR STUDY")
    print("=" * 100)
    print(f"Problems       : {problems}")
    print(f"x values       : {x_values}")
    print(f"Total cases    : {len(problems) * len(x_values)}")
    print(f"Target Lmin    : {base_cfg.target_min_length} in")
    print(f"Output folder  : {out_dir}")
    print("=" * 100 + "\n")

    case_counter = 0

    for problem_name in problems:
        for x in x_values:
            case_counter += 1

            cfg = replace(
                base_cfg,
                problem_name=problem_name,
                fmax_factor=x,
            )

            print("\n" + "#" * 100)
            print(f"Running case {case_counter}/16: problem={problem_name}, x={x}")
            print(f"fmax = 1 / ({x} * {cfg.target_min_length}) = {cfg.fmax:.6g} cycles/in")
            print("#" * 100 + "\n")

            try:
                result = run_one_case(cfg)
                results.append(result)

                save_study_csv(results, out_dir)
                make_study_summary_plots(results, out_dir)

            except Exception as e:
                print(f"ERROR in case problem={problem_name}, x={x}")
                print(str(e))

                results.append({
                    "problem_name": problem_name,
                    "fmax_factor_x": x,
                    "target_min_length": cfg.target_min_length,
                    "fmax": cfg.fmax,
                    "min_fourier_wavelength": cfg.min_fourier_wavelength,
                    "half_wavelength_estimate": cfg.half_wavelength_estimate,
                    "final_compliance": np.nan,
                    "final_volfrac": np.nan,
                    "final_epoch": np.nan,
                    "solid_min_thickness": np.nan,
                    "solid_violation_fraction": np.nan,
                    "void_min_thickness": np.nan,
                    "void_violation_fraction": np.nan,
                    "case_dir": "",
                })

                save_study_csv(results, out_dir)
                make_study_summary_plots(results, out_dir)
                clean_cuda_memory()

    save_study_csv(results, out_dir)
    make_study_summary_plots(results, out_dir)

    print("\n" + "=" * 100)
    print("FMAX FACTOR STUDY COMPLETE")
    print("=" * 100)
    print(f"Summary CSV and plots saved in: {out_dir}")
    print("=" * 100)

    return results


# ============================================================
# Block 14 - Main
# ============================================================

if __name__ == "__main__":
    results = run_fmax_factor_study()