# -*- coding: utf-8 -*-
"""Upsampling_Validation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ciDytEgJkFTrGf0Aqqs5rFY_XVLU71B
"""

# ============================================================
# TONN-FF with Physical Length-Scale Control
#
# Clean version:
# 1. Single Config source of truth
# 2. Bounded disk Fourier sampling only
# 3. Physical coordinate domain
# 4. High-resolution local thickness verification
# 5. Critical circle overlay
# ============================================================

from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Dict, Any
import math
import sys
import gc

import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import scipy.ndimage as ndi
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter
from matplotlib.patches import Circle

import torch
import torch.nn as nn

try:
    from skimage.morphology import skeletonize
    SKIMAGE_AVAILABLE = True
except Exception:
    SKIMAGE_AVAILABLE = False
    skeletonize = None

try:
    from IPython.display import display, Image as IPyImage
except Exception:
    display = None
    IPyImage = None


gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    print(torch.cuda.get_device_name(0))
    print(torch.cuda.memory_summary(device=0, abbreviated=True))


# ============================================================
# Block 1 - Configuration
# ============================================================

@dataclass
class Config:
    # --------------------------------------------------------
    # Physical domain
    # --------------------------------------------------------
    nelx: int = 90
    nely: int = 30

    # Physical element size, inches
    elem_size_x: float = 0.1
    elem_size_y: float = 0.1

    volfrac: float = 0.4
    problem_name: str = "MBB"
    # Options:
    # "Tip_loaded_cantilever", "Mid_loaded_cantilever", "MBB"

    # --------------------------------------------------------
    # Material / FE
    # --------------------------------------------------------
    E0: float = 1.0
    Emin: float = 1e-9
    nu: float = 0.3
    plane_stress: bool = True
    penal: float = 3.0

    # --------------------------------------------------------
    # Bounded-disk Fourier feature settings
    # --------------------------------------------------------
    num_fourier_features: int = 512
    fourier_seed: int = 0

    # Physical target minimum feature size, inches
    target_min_length: float = 0.3

    # If True:
    #     fmax = 1 / (2 * target_min_length)
    # If False:
    #     fmax = 1 / target_min_length
    use_half_wavelength_rule: bool = True

    # --------------------------------------------------------
    # Decoder MLP
    # --------------------------------------------------------
    num_hidden_layers: int = 4
    hidden_width: int = 256

    # --------------------------------------------------------
    # Optimizer
    # --------------------------------------------------------
    lr: float = 1e-3
    max_epochs: int = 1000

    # --------------------------------------------------------
    # One-sided ALM settings for V(rho) <= V0
    # --------------------------------------------------------
    alm_lambda0: float = 0.0
    alm_mu0: float = 5.0
    alm_update_every: int = 50
    alm_mu_scale: float = 1.2
    alm_mu_max: float = 50.0

    # --------------------------------------------------------
    # Stopping rule
    # --------------------------------------------------------
    rho_change_max_tol: float = 0.05
    volfrac_residual_tol: float = 0.001
    compliance_rel_improve_tol: float = 5e-4
    compliance_window: int = 10
    patience: int = 5
    min_epochs_before_stop: int = 100

    # --------------------------------------------------------
    # High-resolution reconstruction
    # --------------------------------------------------------
    samples_per_element: int = 15
    gif_frame_every: int = 20
    gif_fps: int = 6

    # --------------------------------------------------------
    # Length-scale diagnostics
    # --------------------------------------------------------
    density_threshold: float = 0.5
    compute_void_thickness: bool = True
    min_component_area_pixels: int = 20

    # --------------------------------------------------------
    # Misc
    # --------------------------------------------------------
    print_every: int = 25
    save_outputs: bool = True
    out_dir: str = "/content/tounn_physical_lengthscale_outputs"
    device: str = "auto"
    dtype: torch.dtype = torch.float32

    @property
    def lx(self) -> float:
        return self.nelx * self.elem_size_x

    @property
    def ly(self) -> float:
        return self.nely * self.elem_size_y

    @property
    def fmax(self) -> float:
        if self.target_min_length <= 0:
            raise ValueError("target_min_length must be positive.")

        if self.use_half_wavelength_rule:
            return 1.0 / (6 * self.target_min_length)

        return 1.0 / self.target_min_length

    @property
    def min_fourier_wavelength(self) -> float:
        return 1.0 / self.fmax


# ============================================================
# Block 2 - Runtime helpers
# ============================================================

def resolve_device(device_string: str) -> torch.device:
    if device_string == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device_string == "cuda" and not torch.cuda.is_available():
        print("Requested CUDA, but no GPU is available. Falling back to CPU.")
        return torch.device("cpu")
    return torch.device(device_string)


def running_in_colab() -> bool:
    return "google.colab" in sys.modules


def safe_logit(p: float, eps: float = 1e-6) -> float:
    p = float(np.clip(p, eps, 1.0 - eps))
    return math.log(p / (1.0 - p))


def make_problem_tag(problem_name: str) -> str:
    if problem_name == "Tip_loaded_cantilever":
        return "Tip_loaded_Cantilever"
    if problem_name == "Mid_loaded_cantilever":
        return "Mid_loaded_Cantilever"
    if problem_name == "MBB":
        return "MBB"
    return problem_name.strip().replace(" ", "_")


def make_run_tag(cfg: Config) -> str:
    problem_tag = make_problem_tag(cfg.problem_name)
    ff_tag = f"BoundedDiskFmax{cfg.fmax:g}_Lmin{cfg.target_min_length:g}"
    mesh_tag = f"TM{cfg.nelx}X{cfg.nely}"
    elem_tag = f"Elem{cfg.elem_size_x:g}X{cfg.elem_size_y:g}"
    vf_tag = f"VF{cfg.volfrac:g}"

    return f"{ff_tag}_{problem_tag}_{mesh_tag}_{elem_tag}_{vf_tag}"


# ============================================================
# Block 3 - Bounded Disk Fourier Feature Map
# ============================================================

class BoundedDiskFourierFeatureMap(nn.Module):
    """
    Bounded disk Fourier feature map.

    Each frequency vector is sampled as:

        b_i = r_i [cos(theta_i), sin(theta_i)]

    where:

        theta_i ~ U(0, 2pi)
        r_i     ~ U(0, fmax)

    Therefore:

        ||b_i|| <= fmax

    If x and y are in inches, then b_i has units of cycles/inch.

    Output:

        gamma(x) = [cos(2pi x B^T), sin(2pi x B^T)]
    """

    def __init__(
        self,
        in_dim: int,
        num_fourier_features: int,
        fmax: float,
        seed: int = 0,
    ):
        super().__init__()

        if in_dim != 2:
            raise ValueError("This Fourier map assumes 2D coordinates.")

        if fmax <= 0:
            raise ValueError("fmax must be positive.")

        gen = torch.Generator(device="cpu")
        gen.manual_seed(seed)

        theta = 2.0 * math.pi * torch.rand(num_fourier_features, generator=gen)
        r = fmax * torch.rand(num_fourier_features, generator=gen)

        bx = r * torch.cos(theta)
        by = r * torch.sin(theta)

        B = torch.stack([bx, by], dim=1)

        self.fmax = fmax
        self.register_buffer("B", B)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        xb = 2.0 * math.pi * (x @ self.B.T)
        return torch.cat([torch.cos(xb), torch.sin(xb)], dim=1)


# ============================================================
# Block 4 - Mesh, BCs, and Q4 FE helpers
# ============================================================

def node_id(ix, iy, nelx):
    return iy * (nelx + 1) + ix


def q4_element_stiffness_rect(dx, dy, nu, plane_stress=True):
    if plane_stress:
        D = (1.0 / (1.0 - nu**2)) * np.array([
            [1.0, nu, 0.0],
            [nu, 1.0, 0.0],
            [0.0, 0.0, (1.0 - nu) / 2.0],
        ], dtype=float)
    else:
        D = ((1.0 - nu) / ((1.0 + nu) * (1.0 - 2.0 * nu))) * np.array([
            [1.0, nu / (1.0 - nu), 0.0],
            [nu / (1.0 - nu), 1.0, 0.0],
            [0.0, 0.0, (1.0 - 2.0 * nu) / (2.0 * (1.0 - nu))],
        ], dtype=float)

    xnod = np.array([-dx / 2, dx / 2, dx / 2, -dx / 2], dtype=float)
    ynod = np.array([-dy / 2, -dy / 2, dy / 2, dy / 2], dtype=float)

    gp = 1.0 / np.sqrt(3.0)
    gauss_points = [(-gp, -gp), (gp, -gp), (gp, gp), (-gp, gp)]
    KE = np.zeros((8, 8), dtype=float)

    for xi, eta in gauss_points:
        dN_dxi = 0.25 * np.array([
            -(1.0 - eta),
             (1.0 - eta),
             (1.0 + eta),
            -(1.0 + eta),
        ], dtype=float)

        dN_deta = 0.25 * np.array([
            -(1.0 - xi),
            -(1.0 + xi),
             (1.0 + xi),
             (1.0 - xi),
        ], dtype=float)

        J = np.array([
            [np.dot(dN_dxi, xnod), np.dot(dN_deta, xnod)],
            [np.dot(dN_dxi, ynod), np.dot(dN_deta, ynod)],
        ], dtype=float)

        invJ = np.linalg.inv(J)
        dN = np.vstack((dN_dxi, dN_deta))
        dN_xy = invJ @ dN

        dN_dx = dN_xy[0, :]
        dN_dy = dN_xy[1, :]
        detJ = np.linalg.det(J)

        Bmat = np.zeros((3, 8), dtype=float)
        for a in range(4):
            Bmat[0, 2 * a] = dN_dx[a]
            Bmat[1, 2 * a + 1] = dN_dy[a]
            Bmat[2, 2 * a] = dN_dy[a]
            Bmat[2, 2 * a + 1] = dN_dx[a]

        KE += Bmat.T @ D @ Bmat * detJ

    return KE


def get_loads_and_bcs(nelx, nely, problem_name):
    ndof = 2 * (nelx + 1) * (nely + 1)
    F = np.zeros(ndof, dtype=float)

    if problem_name == "Tip_loaded_cantilever":
        load_node = node_id(nelx, nely, nelx)
        F[2 * load_node + 1] = -1.0

        fixed = []
        for iy in range(nely + 1):
            n = node_id(0, iy, nelx)
            fixed.extend([2 * n, 2 * n + 1])

    elif problem_name == "Mid_loaded_cantilever":
        load_node = node_id(nelx, nely // 2, nelx)
        F[2 * load_node + 1] = -1.0

        fixed = []
        for iy in range(nely + 1):
            n = node_id(0, iy, nelx)
            fixed.extend([2 * n, 2 * n + 1])

    elif problem_name == "MBB":
        load_node = node_id(0, nely, nelx)
        F[2 * load_node + 1] = -1.0

        fixed = []
        for iy in range(nely + 1):
            n = node_id(0, iy, nelx)
            fixed.append(2 * n)

        br = node_id(nelx, 0, nelx)
        fixed.append(2 * br + 1)

    else:
        raise ValueError("Unknown problem_name.")

    fixed = np.array(sorted(set(fixed)), dtype=int)
    free = np.setdiff1d(np.arange(ndof), fixed)

    return F, fixed, free


def build_problem_data(cfg):
    nelx, nely = cfg.nelx, cfg.nely
    dx = cfg.elem_size_x
    dy = cfg.elem_size_y

    nele = nelx * nely
    ndof = 2 * (nelx + 1) * (nely + 1)

    centers = np.zeros((nele, 2), dtype=float)
    elem_areas = np.full(nele, dx * dy, dtype=float)
    edofMat = np.zeros((nele, 8), dtype=int)

    e = 0
    for ey in range(nely):
        for ex in range(nelx):
            centers[e, :] = [
                (ex + 0.5) * dx,
                (ey + 0.5) * dy,
            ]

            n1 = node_id(ex, ey, nelx)
            n2 = node_id(ex + 1, ey, nelx)
            n3 = node_id(ex + 1, ey + 1, nelx)
            n4 = node_id(ex, ey + 1, nelx)

            edofMat[e, :] = [
                2 * n1, 2 * n1 + 1,
                2 * n2, 2 * n2 + 1,
                2 * n3, 2 * n3 + 1,
                2 * n4, 2 * n4 + 1,
            ]

            e += 1

    iK = np.kron(edofMat, np.ones((8, 1), dtype=int)).ravel()
    jK = np.kron(edofMat, np.ones((1, 8), dtype=int)).ravel()

    KE = q4_element_stiffness_rect(dx, dy, cfg.nu, cfg.plane_stress)
    F, fixed, free = get_loads_and_bcs(nelx, nely, cfg.problem_name)

    return {
        "centers": centers,
        "elem_areas": elem_areas,
        "edofMat": edofMat,
        "iK": iK,
        "jK": jK,
        "KE": KE,
        "F": F,
        "fixed": fixed,
        "free": free,
        "ndof": ndof,
        "nele": nele,
        "dx": dx,
        "dy": dy,
    }


# ============================================================
# Block 5 - FEA black box
# ============================================================

def fea_black_box(rho_torch, problem_data, cfg):
    rho = rho_torch.detach().cpu().numpy().astype(float)
    rho = np.clip(rho, 1e-9, 1.0)

    E_e = cfg.Emin + (rho ** cfg.penal) * (cfg.E0 - cfg.Emin)
    sK = np.outer(E_e, problem_data["KE"].ravel()).ravel()

    K = sp.coo_matrix(
        (sK, (problem_data["iK"], problem_data["jK"])),
        shape=(problem_data["ndof"], problem_data["ndof"]),
    ).tocsc()

    K = 0.5 * (K + K.T)

    U = np.zeros(problem_data["ndof"], dtype=float)
    free = problem_data["free"]

    U[free] = spla.spsolve(K[free, :][:, free], problem_data["F"][free])

    Ue = U[problem_data["edofMat"]]
    Je0 = np.einsum("ij,ij->i", Ue @ problem_data["KE"], Ue)

    compliance = np.sum(E_e * Je0)

    return Je0, float(compliance)


def compute_windowed_compliance_improvement(compliance_history, window):
    if len(compliance_history) < 2 * window:
        return np.inf

    older = np.mean(compliance_history[-2 * window:-window])
    recent = np.mean(compliance_history[-window:])

    return abs(recent - older) / max(abs(older), 1e-12)


# ============================================================
# Block 6 - Fourier-feature density network
# ============================================================

class FourierDensityNet(nn.Module):
    def __init__(self, cfg: Config):
        super().__init__()

        self.fourier = BoundedDiskFourierFeatureMap(
            in_dim=2,
            num_fourier_features=cfg.num_fourier_features,
            fmax=cfg.fmax,
            seed=cfg.fourier_seed,
        )

        input_dim = 2 * cfg.num_fourier_features
        in_dim = input_dim

        self.hidden_linears = nn.ModuleList()

        for _ in range(cfg.num_hidden_layers):
            layer = nn.Linear(in_dim, cfg.hidden_width)
            self.hidden_linears.append(layer)
            in_dim = cfg.hidden_width

        self.out = nn.Linear(in_dim, 1)
        self.activation = nn.LeakyReLU(negative_slope=0.01)

        self.reset_parameters(cfg.volfrac)

    def reset_parameters(self, volfrac: float):
        for layer in self.hidden_linears:
            nn.init.orthogonal_(layer.weight)
            nn.init.zeros_(layer.bias)

        nn.init.normal_(self.out.weight, mean=0.0, std=1e-4)
        nn.init.constant_(self.out.bias, safe_logit(volfrac))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        z = self.fourier(x)

        h = z
        for layer in self.hidden_linears:
            h = self.activation(layer(h))

        logits = self.out(h)
        rho = torch.sigmoid(logits).squeeze(1)

        return rho


# ============================================================
# Block 7 - High-resolution sampling
# ============================================================

def sample_highres_density(model, cfg, device):
    s = cfg.samples_per_element

    nx_hr = cfg.nelx * s
    ny_hr = cfg.nely * s

    dx_hr = cfg.lx / nx_hr
    dy_hr = cfg.ly / ny_hr

    xs = (np.arange(nx_hr) + 0.5) * dx_hr
    ys = (np.arange(ny_hr) + 0.5) * dy_hr

    XX, YY = np.meshgrid(xs, ys)
    pts = np.column_stack([XX.ravel(), YY.ravel()])

    with torch.no_grad():
        model.eval()
        pts_t = torch.tensor(pts, dtype=cfg.dtype, device=device)
        rho_hr = model(pts_t).detach().cpu().numpy().reshape(ny_hr, nx_hr)

    return rho_hr


def get_final_density(model, cfg, problem_data, device):
    coords = torch.tensor(problem_data["centers"], dtype=cfg.dtype, device=device)

    with torch.no_grad():
        model.eval()
        rho = model(coords).detach().cpu().numpy().reshape(cfg.nely, cfg.nelx)

    return rho


# ============================================================
# Block 8 - Length-scale diagnostics
# ============================================================

def remove_small_components(mask: np.ndarray, min_area_pixels: int) -> np.ndarray:
    if min_area_pixels <= 0:
        return mask.astype(bool)

    labels, nlab = ndi.label(mask)

    if nlab == 0:
        return mask.astype(bool)

    counts = np.bincount(labels.ravel())
    keep = np.zeros_like(counts, dtype=bool)
    keep[counts >= min_area_pixels] = True
    keep[0] = False

    return keep[labels]


def compute_skeleton(mask: np.ndarray) -> np.ndarray:
    mask = mask.astype(bool)

    if SKIMAGE_AVAILABLE:
        return skeletonize(mask)

    dist = ndi.distance_transform_edt(mask)
    local_max = dist == ndi.maximum_filter(dist, size=3)

    return local_max & mask


def analyze_region_thickness(
    region_mask: np.ndarray,
    dx: float,
    dy: float,
    target_min_length: float,
    min_component_area_pixels: int = 20,
) -> Dict[str, Any]:

    region_mask = region_mask.astype(bool)
    region_mask = remove_small_components(region_mask, min_component_area_pixels)

    if np.sum(region_mask) == 0:
        return {
            "valid": False,
            "message": "Region mask is empty.",
        }

    dist = ndi.distance_transform_edt(region_mask, sampling=(dy, dx))
    skel = compute_skeleton(region_mask)
    valid_skel = skel & (dist > 0.0)

    if np.sum(valid_skel) == 0:
        return {
            "valid": False,
            "message": "Skeleton is empty.",
            "distance": dist,
            "skeleton": skel,
        }

    thickness = 2.0 * dist

    skel_values = thickness[valid_skel]
    candidate_indices = np.flatnonzero(valid_skel)

    min_local_index = int(np.argmin(skel_values))
    min_flat_index = int(candidate_indices[min_local_index])
    row, col = np.unravel_index(min_flat_index, region_mask.shape)

    min_thickness = float(thickness[row, col])
    local_radius = float(dist[row, col])

    violation_mask = valid_skel & (thickness < target_min_length)
    violation_fraction = float(np.sum(violation_mask) / max(np.sum(valid_skel), 1))

    return {
        "valid": True,
        "distance": dist,
        "thickness": thickness,
        "skeleton": skel,
        "valid_skeleton": valid_skel,
        "violation_mask": violation_mask,
        "min_thickness": min_thickness,
        "critical_row": int(row),
        "critical_col": int(col),
        "critical_radius": local_radius,
        "violation_fraction": violation_fraction,
        "num_skeleton_pixels": int(np.sum(valid_skel)),
    }


def analyze_lengthscale(rho_hr: np.ndarray, cfg: Config) -> Dict[str, Any]:
    ny_hr, nx_hr = rho_hr.shape

    dx_hr = cfg.lx / nx_hr
    dy_hr = cfg.ly / ny_hr

    solid_mask = rho_hr >= cfg.density_threshold
    void_mask = ~solid_mask

    solid_result = analyze_region_thickness(
        region_mask=solid_mask,
        dx=dx_hr,
        dy=dy_hr,
        target_min_length=cfg.target_min_length,
        min_component_area_pixels=cfg.min_component_area_pixels,
    )

    if cfg.compute_void_thickness:
        void_result = analyze_region_thickness(
            region_mask=void_mask,
            dx=dx_hr,
            dy=dy_hr,
            target_min_length=cfg.target_min_length,
            min_component_area_pixels=cfg.min_component_area_pixels,
        )
    else:
        void_result = {
            "valid": False,
            "message": "Void thickness not requested.",
        }

    return {
        "dx_hr": dx_hr,
        "dy_hr": dy_hr,
        "solid_mask": solid_mask,
        "void_mask": void_mask,
        "solid": solid_result,
        "void": void_result,
    }


def pixel_to_physical(row: int, col: int, cfg: Config, rho_hr: np.ndarray):
    ny_hr, nx_hr = rho_hr.shape
    dx_hr = cfg.lx / nx_hr
    dy_hr = cfg.ly / ny_hr

    x = (col + 0.5) * dx_hr
    y = (row + 0.5) * dy_hr

    return x, y


def save_lengthscale_summary(length_result: Dict[str, Any], cfg: Config, path: Optional[Path]):
    solid = length_result["solid"]
    void = length_result["void"]

    lines = []
    lines.append("Length-scale diagnostic summary")
    lines.append("=" * 70)
    lines.append(f"Problem                         : {cfg.problem_name}")
    lines.append(f"Mesh                            : {cfg.nelx} x {cfg.nely}")
    lines.append(f"Element size                    : {cfg.elem_size_x:.6g} x {cfg.elem_size_y:.6g} in")
    lines.append(f"Physical domain                 : {cfg.lx:.6g} x {cfg.ly:.6g} in")
    lines.append(f"Volume fraction                 : {cfg.volfrac:.6g}")
    lines.append(f"Fourier sampling                : bounded_disk")
    lines.append(f"Number of Fourier features M    : {cfg.num_fourier_features}")
    lines.append(f"Target minimum length           : {cfg.target_min_length:.6g} in")
    lines.append(f"Fourier fmax                    : {cfg.fmax:.6g} cycles/in")
    lines.append(f"Minimum Fourier wavelength      : {cfg.min_fourier_wavelength:.6g} in")
    lines.append(f"Half wavelength estimate        : {0.5 * cfg.min_fourier_wavelength:.6g} in")
    lines.append(f"Density threshold               : {cfg.density_threshold:.6g}")
    lines.append(f"High-res dx, dy                 : {length_result['dx_hr']:.6g}, {length_result['dy_hr']:.6g} in")
    lines.append("")

    if solid.get("valid", False):
        lines.append("Solid thickness:")
        lines.append(f"  Minimum solid thickness       : {solid['min_thickness']:.6g} in")
        lines.append(f"  Critical solid radius         : {solid['critical_radius']:.6g} in")
        lines.append(f"  Solid violation fraction      : {solid['violation_fraction']:.6g}")
        lines.append(f"  Solid skeleton pixels         : {solid['num_skeleton_pixels']}")
    else:
        lines.append("Solid thickness:")
        lines.append(f"  Not valid: {solid.get('message', 'Unknown issue')}")

    lines.append("")

    if void.get("valid", False):
        lines.append("Void thickness:")
        lines.append(f"  Minimum void thickness        : {void['min_thickness']:.6g} in")
        lines.append(f"  Critical void radius          : {void['critical_radius']:.6g} in")
        lines.append(f"  Void violation fraction       : {void['violation_fraction']:.6g}")
        lines.append(f"  Void skeleton pixels          : {void['num_skeleton_pixels']}")
    else:
        lines.append("Void thickness:")
        lines.append(f"  Not valid: {void.get('message', 'Unknown issue')}")

    text = "\n".join(lines)
    print(text)

    if path is not None:
        path.write_text(text)


# ============================================================
# Block 9 - Plotting
# ============================================================

def plot_topology_with_critical_circle(
    rho_hr: np.ndarray,
    length_result: Dict[str, Any],
    cfg: Config,
    out_path: Optional[Path] = None,
):
    solid = length_result["solid"]

    fig, ax = plt.subplots(figsize=(10, 5))

    ax.imshow(
        rho_hr,
        cmap="gray_r",
        origin="lower",
        vmin=0.0,
        vmax=1.0,
        extent=[0, cfg.lx, 0, cfg.ly],
        aspect="equal",
        interpolation="nearest",
    )

    ax.set_xlabel("x [in]")
    ax.set_ylabel("y [in]")

    title = (
        f"High-Resolution Topology with Critical Length-Scale Circle\n"
        f"Target minimum length = {cfg.target_min_length:g} in"
    )

    if solid.get("valid", False):
        row = solid["critical_row"]
        col = solid["critical_col"]
        xcrit, ycrit = pixel_to_physical(row, col, cfg, rho_hr)

        target_radius = cfg.target_min_length / 2.0
        measured_radius = solid["critical_radius"]

        target_circle = Circle(
            (xcrit, ycrit),
            target_radius,
            fill=False,
            linewidth=2.0,
            edgecolor="red",
            label=f"Target circle, diameter = {cfg.target_min_length:g} in",
        )

        measured_circle = Circle(
            (xcrit, ycrit),
            measured_radius,
            fill=False,
            linewidth=1.5,
            linestyle="--",
            edgecolor="blue",
            label=f"Measured circle, diameter = {solid['min_thickness']:.4g} in",
        )

        ax.add_patch(target_circle)
        ax.add_patch(measured_circle)
        ax.plot(xcrit, ycrit, marker="x", markersize=8, color="red")

        title += f"\nMeasured minimum solid thickness = {solid['min_thickness']:.4g} in"
        ax.legend(loc="upper right")

    else:
        title += "\nSolid thickness analysis unavailable"

    ax.set_title(title)
    plt.tight_layout()

    if out_path is not None:
        fig.savefig(out_path, dpi=300, bbox_inches="tight")

    plt.show()
    plt.close(fig)


def plot_thickness_violation_map(
    rho_hr: np.ndarray,
    length_result: Dict[str, Any],
    cfg: Config,
    out_path: Optional[Path] = None,
):
    solid = length_result["solid"]

    fig, ax = plt.subplots(figsize=(10, 5))

    ax.imshow(
        rho_hr,
        cmap="gray_r",
        origin="lower",
        vmin=0.0,
        vmax=1.0,
        extent=[0, cfg.lx, 0, cfg.ly],
        aspect="equal",
        interpolation="nearest",
    )

    if solid.get("valid", False):
        violation = solid["violation_mask"]
        yy, xx = np.where(violation)

        if len(xx) > 0:
            dx_hr = length_result["dx_hr"]
            dy_hr = length_result["dy_hr"]

            x_phys = (xx + 0.5) * dx_hr
            y_phys = (yy + 0.5) * dy_hr

            ax.scatter(
                x_phys,
                y_phys,
                s=4,
                c="red",
                label=f"solid skeleton thickness < {cfg.target_min_length:g} in",
            )
            ax.legend(loc="upper right")

        title = (
            f"Solid Thickness Violation Map\n"
            f"Violation fraction = {solid['violation_fraction']:.4g}"
        )
    else:
        title = "Solid Thickness Violation Map Unavailable"

    ax.set_xlabel("x [in]")
    ax.set_ylabel("y [in]")
    ax.set_title(title)

    plt.tight_layout()

    if out_path is not None:
        fig.savefig(out_path, dpi=300, bbox_inches="tight")

    plt.show()
    plt.close(fig)


def plot_thickness_field(
    length_result: Dict[str, Any],
    cfg: Config,
    out_path: Optional[Path] = None,
):
    solid = length_result["solid"]

    if not solid.get("valid", False):
        print("Solid thickness field unavailable.")
        return

    thickness = solid["thickness"].copy()
    solid_mask = length_result["solid_mask"]
    thickness[~solid_mask] = np.nan

    fig, ax = plt.subplots(figsize=(10, 5))

    im = ax.imshow(
        thickness,
        origin="lower",
        extent=[0, cfg.lx, 0, cfg.ly],
        aspect="equal",
        interpolation="nearest",
    )

    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label("Local solid thickness [in]")

    ax.contour(
        thickness,
        levels=[cfg.target_min_length],
        origin="lower",
        extent=[0, cfg.lx, 0, cfg.ly],
        linewidths=1.5,
        colors="red",
    )

    ax.set_xlabel("x [in]")
    ax.set_ylabel("y [in]")
    ax.set_title(
        f"Local Solid Thickness Field\n"
        f"Red contour = target minimum length {cfg.target_min_length:g} in"
    )

    plt.tight_layout()

    if out_path is not None:
        fig.savefig(out_path, dpi=300, bbox_inches="tight")

    plt.show()
    plt.close(fig)


def save_highres_gif(frames, cfg, out_path):
    if len(frames) == 0:
        return

    fig, ax = plt.subplots(figsize=(8, 4))

    im = ax.imshow(
        frames[0]["grid"],
        cmap="gray_r",
        origin="lower",
        vmin=0.0,
        vmax=1.0,
        extent=[0, cfg.lx, 0, cfg.ly],
        aspect="equal",
        interpolation="nearest",
    )

    ax.set_xlabel("x [in]")
    ax.set_ylabel("y [in]")

    title = ax.set_title("")
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label("Density")

    def update(i):
        fr = frames[i]
        im.set_data(fr["grid"])
        title.set_text(
            f"High-res density | epoch {fr['epoch']} | "
            f"C = {fr['compliance']:.4f} | VF = {fr['volfrac']:.4f}"
        )
        return [im, title]

    anim = FuncAnimation(
        fig,
        update,
        frames=len(frames),
        interval=1000 // max(cfg.gif_fps, 1),
        blit=False,
    )

    anim.save(out_path, writer=PillowWriter(fps=cfg.gif_fps))
    plt.close(fig)


# ============================================================
# Block 10 - Training loop
# ============================================================

def train(cfg):
    device = resolve_device(cfg.device)
    problem_data = build_problem_data(cfg)

    coords = torch.tensor(problem_data["centers"], dtype=cfg.dtype, device=device)
    elem_areas = torch.tensor(problem_data["elem_areas"], dtype=cfg.dtype, device=device)

    V_total = float(problem_data["elem_areas"].sum())
    V_star_abs = cfg.volfrac * V_total

    model = FourierDensityNet(cfg).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg.lr)

    previous_rho = None
    patience_counter = 0
    frames = []

    alm_lambda = float(cfg.alm_lambda0)
    alm_mu = float(cfg.alm_mu0)
    prev_g_plus_for_mu = None

    J0 = None

    history = {
        "epoch": [],
        "compliance": [],
        "volfrac": [],
        "loss": [],
        "rho_change_max": [],
        "volfrac_residual": [],
        "compliance_rel_improve": [],
        "patience_counter": [],
        "alm_lambda": [],
        "alm_mu": [],
        "g_plus": [],
    }

    run_tag = make_run_tag(cfg)

    print("=" * 78)
    print("TONN-FF with bounded-disk physical Fourier length-scale control")
    print(f"Run tag                   : {run_tag}")
    print(f"Device                    : {device}")
    print(f"Problem                   : {cfg.problem_name}")
    print(f"Mesh                      : {cfg.nelx} x {cfg.nely}")
    print(f"Element size              : {cfg.elem_size_x} in x {cfg.elem_size_y} in")
    print(f"Physical domain           : {cfg.lx} in x {cfg.ly} in")
    print(f"Target volume fraction    : {cfg.volfrac}")
    print(f"SIMP penal                : {cfg.penal}")
    print(f"Fourier sampling          : bounded_disk")
    print(f"Fourier features M        : {cfg.num_fourier_features}")
    print(f"Fourier seed              : {cfg.fourier_seed}")
    print(f"Target minimum length     : {cfg.target_min_length} in")
    print(f"Bounded disk fmax         : {cfg.fmax} cycles/in")
    print(f"Minimum FF wavelength     : {cfg.min_fourier_wavelength} in")
    print(f"Half wavelength estimate  : {0.5 * cfg.min_fourier_wavelength} in")
    print(f"Density threshold         : {cfg.density_threshold}")
    print(f"Decoder layers / width    : {cfg.num_hidden_layers} / {cfg.hidden_width}")
    print(f"Adam lr                   : {cfg.lr}")
    print(f"Max iterations            : {cfg.max_epochs}")
    print("=" * 78)

    for epoch in range(cfg.max_epochs):
        model.train()
        optimizer.zero_grad()

        rho = model(coords).clamp(1e-6, 1.0 - 1e-6)

        Je0_np, compliance = fea_black_box(rho, problem_data, cfg)
        Je0 = torch.tensor(Je0_np, dtype=cfg.dtype, device=device)

        V_abs = torch.sum(rho * elem_areas)
        volfrac_current = V_abs / V_total
        volfrac_residual = volfrac_current / cfg.volfrac - 1.0

        g_v = (V_abs / V_star_abs) - 1.0
        g_plus = torch.clamp(g_v, min=0.0)

        if epoch == 0:
            J0 = max(float(compliance), 1e-12)

        loss = (compliance / J0) + alm_lambda * g_plus + 0.5 * alm_mu * (g_plus ** 2)

        dJ_drho = (
            -cfg.penal
            * (cfg.E0 - cfg.Emin)
            * torch.pow(rho.detach(), cfg.penal - 1.0)
            * Je0
            / J0
        )

        dVabs_drho = elem_areas
        dg_drho = dVabs_drho / V_star_abs

        active_mask = (g_v.detach() > 0.0).to(cfg.dtype)

        dL_drho = dJ_drho + (
            alm_lambda + alm_mu * g_plus.detach()
        ) * active_mask * dg_drho

        rho.backward(dL_drho)
        optimizer.step()

        if (epoch + 1) % cfg.alm_update_every == 0:
            g_scalar = float(g_v.detach().cpu())
            g_plus_scalar = max(g_scalar, 0.0)

            alm_lambda = max(0.0, alm_lambda + alm_mu * g_scalar)

            if prev_g_plus_for_mu is not None and g_plus_scalar > 0.25 * prev_g_plus_for_mu:
                alm_mu = min(cfg.alm_mu_max, alm_mu * cfg.alm_mu_scale)

            prev_g_plus_for_mu = g_plus_scalar

        rho_cpu = rho.detach().cpu().numpy()

        if previous_rho is None:
            rho_change_max = np.inf
        else:
            rho_change_max = float(np.max(np.abs(rho_cpu - previous_rho)))

        previous_rho = rho_cpu.copy()

        history["epoch"].append(epoch)
        history["compliance"].append(float(compliance))
        history["volfrac"].append(float(volfrac_current.detach().cpu()))
        history["loss"].append(float(loss.detach().cpu()))
        history["rho_change_max"].append(rho_change_max)
        history["volfrac_residual"].append(float(volfrac_residual.detach().cpu()))
        history["alm_lambda"].append(float(alm_lambda))
        history["alm_mu"].append(float(alm_mu))
        history["g_plus"].append(float(g_plus.detach().cpu()))

        compliance_rel_improve = compute_windowed_compliance_improvement(
            history["compliance"],
            cfg.compliance_window,
        )
        history["compliance_rel_improve"].append(compliance_rel_improve)

        enough_epochs = epoch >= cfg.min_epochs_before_stop
        volume_ok = abs(float(volfrac_residual.detach().cpu())) < cfg.volfrac_residual_tol
        rho_ok = rho_change_max < cfg.rho_change_max_tol
        compliance_ok = compliance_rel_improve < cfg.compliance_rel_improve_tol

        if enough_epochs and volume_ok or rho_ok and compliance_ok:
            patience_counter += 1
        else:
            patience_counter = 0

        history["patience_counter"].append(patience_counter)

        if (epoch % cfg.gif_frame_every == 0) or (epoch == cfg.max_epochs - 1):
            rho_hr = sample_highres_density(model, cfg, device)
            frames.append({
                "epoch": epoch,
                "grid": rho_hr,
                "compliance": float(compliance),
                "volfrac": float(volfrac_current.detach().cpu()),
            })

        if epoch % cfg.print_every == 0 or epoch == cfg.max_epochs - 1:
            improve_str = (
                f"{compliance_rel_improve:9.3e}"
                if np.isfinite(compliance_rel_improve)
                else "      inf"
            )

            print(
                f"iter={epoch:5d} | "
                f"Lt={float(loss.detach().cpu()):12.5f} | "
                f"J={float(compliance):12.5f} | "
                f"VF={float(volfrac_current.detach().cpu()):7.4f} | "
                f"gVF={float(volfrac_residual.detach().cpu()):+9.5f} | "
                f"g+={float(g_plus.detach().cpu()):10.4e} | "
                f"lam={float(alm_lambda):10.4e} | "
                f"mu={float(alm_mu):10.4e} | "
                f"max|dRho|={rho_change_max:9.3e} | "
                f"rel dC={improve_str} | "
                f"pat={patience_counter:3d}/{cfg.patience:3d}"
            )

        if patience_counter >= cfg.patience:
            print("\nConverged with sustained density/design stabilization.")
            print(f"Stopped at iteration       : {epoch}")
            print(f"max|rho_k-rho_k-1|         : {rho_change_max:.6e}")
            print(f"|volume residual|          : {abs(float(volfrac_residual.detach().cpu())):.6e}")
            print(f"windowed rel compliance Δ  : {compliance_rel_improve:.6e}")

            if len(frames) == 0 or frames[-1]["epoch"] != epoch:
                rho_hr = sample_highres_density(model, cfg, device)
                frames.append({
                    "epoch": epoch,
                    "grid": rho_hr,
                    "compliance": float(compliance),
                    "volfrac": float(volfrac_current.detach().cpu()),
                })

            break

    return model, history, problem_data, device, frames


# ============================================================
# Block 11 - Result plotting and saving
# ============================================================

def show_and_save_results(model, history, cfg, problem_data, device, frames):
    out_dir = Path(cfg.out_dir)
    run_tag = make_run_tag(cfg)

    if cfg.save_outputs:
        out_dir.mkdir(parents=True, exist_ok=True)

    rho = get_final_density(model, cfg, problem_data, device)
    rho_hr = sample_highres_density(model, cfg, device)
    length_result = analyze_lengthscale(rho_hr, cfg)

    coarse_path = out_dir / f"{run_tag}_final_density_coarse.png"
    highres_path = out_dir / f"{run_tag}_final_highres_raw.png"
    history_path = out_dir / f"{run_tag}_training_history.png"
    gif_path = out_dir / f"{run_tag}_highres_raw_evolution.gif"

    circle_path = out_dir / f"{run_tag}_critical_circle_overlay.png"
    violation_path = out_dir / f"{run_tag}_solid_thickness_violation_map.png"
    thickness_path = out_dir / f"{run_tag}_solid_thickness_field.png"
    summary_path = out_dir / f"{run_tag}_lengthscale_summary.txt"

    plt.figure(figsize=(9, 4))
    plt.imshow(
        rho,
        cmap="gray_r",
        origin="lower",
        extent=[0, cfg.lx, 0, cfg.ly],
        aspect="equal",
    )
    plt.colorbar(label="Density")
    plt.xlabel("x [in]")
    plt.ylabel("y [in]")
    plt.title(
        f"Final coarse density | {cfg.problem_name} | FE {cfg.nelx}x{cfg.nely}\n"
        f"Bounded disk FF | M={cfg.num_fourier_features}, Lmin target={cfg.target_min_length:g} in"
    )
    plt.tight_layout()

    if cfg.save_outputs:
        plt.savefig(coarse_path, dpi=250, bbox_inches="tight")

    plt.show()
    plt.close()

    plt.figure(figsize=(9, 4))
    plt.imshow(
        rho_hr,
        cmap="gray_r",
        origin="lower",
        vmin=0.0,
        vmax=1.0,
        extent=[0, cfg.lx, 0, cfg.ly],
        aspect="equal",
        interpolation="nearest",
    )
    plt.colorbar(label="Density")
    plt.xlabel("x [in]")
    plt.ylabel("y [in]")
    plt.title(
        f"Final high-resolution raw density | {cfg.problem_name}\n"
        f"{cfg.samples_per_element} x {cfg.samples_per_element} samples per element"
    )
    plt.tight_layout()

    if cfg.save_outputs:
        plt.savefig(highres_path, dpi=250, bbox_inches="tight")

    plt.show()
    plt.close()

    fig, axs = plt.subplots(6, 1, figsize=(10, 16), sharex=True)

    axs[0].plot(history["epoch"], history["loss"])
    axs[0].set_ylabel("Total loss")
    axs[0].grid(True, alpha=0.3)

    axs[1].plot(history["epoch"], history["compliance"])
    axs[1].set_ylabel("Compliance")
    axs[1].grid(True, alpha=0.3)

    axs[2].plot(history["epoch"], history["volfrac"])
    axs[2].axhline(cfg.volfrac, linestyle="--")
    axs[2].set_ylabel("Current VF")
    axs[2].grid(True, alpha=0.3)

    axs[3].plot(history["epoch"], history["rho_change_max"])
    axs[3].axhline(cfg.rho_change_max_tol, linestyle="--")
    axs[3].set_ylabel("max|Δrho|")
    axs[3].set_yscale("log")
    axs[3].grid(True, alpha=0.3)

    axs[4].plot(history["epoch"], history["g_plus"], label="g+")
    axs[4].plot(history["epoch"], history["alm_lambda"], label="lambda")
    axs[4].plot(history["epoch"], history["alm_mu"], label="mu")
    axs[4].set_ylabel("ALM control")
    axs[4].set_yscale("log")
    axs[4].grid(True, alpha=0.3)
    axs[4].legend()

    comp_improve = np.array(history["compliance_rel_improve"], dtype=float)
    comp_improve_plot = comp_improve.copy()
    comp_improve_plot[~np.isfinite(comp_improve_plot)] = np.nan

    axs[5].plot(history["epoch"], comp_improve_plot, label="rel compliance change")
    axs[5].axhline(cfg.compliance_rel_improve_tol, linestyle="--", label="tolerance")
    axs[5].plot(history["epoch"], history["patience_counter"], label="patience counter")
    axs[5].set_ylabel("Convergence")
    axs[5].set_xlabel("Iteration")
    axs[5].set_yscale("log")
    axs[5].grid(True, alpha=0.3)
    axs[5].legend()

    fig.tight_layout()

    if cfg.save_outputs:
        fig.savefig(history_path, dpi=250, bbox_inches="tight")

    plt.show()
    plt.close(fig)

    plot_topology_with_critical_circle(
        rho_hr=rho_hr,
        length_result=length_result,
        cfg=cfg,
        out_path=circle_path if cfg.save_outputs else None,
    )

    plot_thickness_violation_map(
        rho_hr=rho_hr,
        length_result=length_result,
        cfg=cfg,
        out_path=violation_path if cfg.save_outputs else None,
    )

    plot_thickness_field(
        length_result=length_result,
        cfg=cfg,
        out_path=thickness_path if cfg.save_outputs else None,
    )

    if cfg.save_outputs:
        save_lengthscale_summary(length_result, cfg, summary_path)
        save_highres_gif(frames, cfg, gif_path)

        print("\nSaved outputs:")
        print(coarse_path)
        print(highres_path)
        print(history_path)
        print(circle_path)
        print(violation_path)
        print(thickness_path)
        print(summary_path)
        print(gif_path)

        if running_in_colab() and display is not None and IPyImage is not None:
            try:
                display(IPyImage(filename=str(gif_path)))
            except Exception:
                pass

    return length_result


# ============================================================
# Block 12 - Coarse-to-fine NN upsampling validity study
# Paste this block after Block 11 and replace your current main() block.
# Also add this import near the top of the file:
#     from dataclasses import dataclass, replace
# or add the small local import below.
# ============================================================

from dataclasses import replace
import csv


def clone_cfg(base_cfg: Config, **updates) -> Config:
    """Create a modified Config without mutating the original."""
    return replace(base_cfg, **updates)


def make_mesh_cfg_from_domain(
    base_cfg: Config,
    nelx: int,
    nely: int,
    lx_fixed: float,
    ly_fixed: float,
    problem_name: str,
    out_dir: str,
) -> Config:
    """
    Create a Config for a requested mesh while keeping the same physical domain.

    This is the most important part of the study:
    when going from 80x40 to 200x100, the element size must become smaller.
    The domain must not accidentally grow.
    """
    return clone_cfg(
        base_cfg,
        nelx=nelx,
        nely=nely,
        elem_size_x=lx_fixed / nelx,
        elem_size_y=ly_fixed / nely,
        problem_name=problem_name,
        out_dir=out_dir,
        samples_per_element=1,
        gif_frame_every=10**9,
        save_outputs=True,
    )


def evaluate_model_on_cfg(model: nn.Module, train_cfg: Config, eval_cfg: Config, device: torch.device):
    """
    Evaluate a trained coordinate NN on the centroids of a different FE mesh,
    then compute the compliance of that density field using the target mesh.

    The NN remains the same. Only the sampling coordinates and FE mesh change.
    """
    eval_data = build_problem_data(eval_cfg)
    coords_eval = torch.tensor(eval_data["centers"], dtype=train_cfg.dtype, device=device)

    model.eval()
    with torch.no_grad():
        rho_eval = model(coords_eval).clamp(1e-6, 1.0 - 1e-6)

    _, compliance_eval = fea_black_box(rho_eval, eval_data, eval_cfg)

    rho_grid = rho_eval.detach().cpu().numpy().reshape(eval_cfg.nely, eval_cfg.nelx)
    vf_eval = float(np.mean(rho_grid))

    return {
        "rho_grid": rho_grid,
        "compliance": float(compliance_eval),
        "volfrac": vf_eval,
        "problem_data": eval_data,
    }


def evaluate_density_grid_on_cfg(rho_grid: np.ndarray, eval_cfg: Config):
    """
    Compute compliance directly from a supplied density grid on eval_cfg.
    This is useful for optional thresholded/binary checks.
    """
    eval_data = build_problem_data(eval_cfg)
    rho_flat = torch.tensor(rho_grid.ravel(), dtype=eval_cfg.dtype)
    _, compliance = fea_black_box(rho_flat, eval_data, eval_cfg)
    return float(compliance), float(np.mean(rho_grid))


def threshold_to_target_vf(rho_grid: np.ndarray, volfrac: float):
    """
    Binarize while approximately preserving the requested volume fraction.
    The highest-density elements are kept as solid.
    """
    flat = rho_grid.ravel()
    nele = flat.size
    keep = int(round(volfrac * nele))
    keep = max(1, min(nele, keep))

    order = np.argsort(flat)[::-1]
    binary = np.zeros_like(flat)
    binary[order[:keep]] = 1.0
    return binary.reshape(rho_grid.shape)


def get_training_final_result(model, history, cfg, problem_data, device):
    """Return final training density, compliance, and volume fraction on its own mesh."""
    rho = get_final_density(model, cfg, problem_data, device)
    compliance = float(history["compliance"][-1])
    vf = float(history["volfrac"][-1])
    return {
        "rho_grid": rho,
        "compliance": compliance,
        "volfrac": vf,
    }


def plot_three_way_comparison(problem_name, coarse_cfg, fine_cfg, coarse_result, upsample_result, fine_result, out_path):
    """
    Plot:
      1. Coarse training result on coarse mesh
      2. Same trained NN sampled/reanalyzed on fine mesh
      3. True fine-mesh training result
    """
    fig, axs = plt.subplots(3, 1, figsize=(11, 10), constrained_layout=True)

    panels = [
        (
            axs[0],
            coarse_result["rho_grid"],
            coarse_cfg,
            f"Coarse trained topology | FE {coarse_cfg.nelx}x{coarse_cfg.nely}",
            coarse_result["compliance"],
            coarse_result["volfrac"],
        ),
        (
            axs[1],
            upsample_result["rho_grid"],
            fine_cfg,
            f"Coarse NN sampled on fine mesh | FE {fine_cfg.nelx}x{fine_cfg.nely}",
            upsample_result["compliance"],
            upsample_result["volfrac"],
        ),
        (
            axs[2],
            fine_result["rho_grid"],
            fine_cfg,
            f"True fine-mesh trained topology | FE {fine_cfg.nelx}x{fine_cfg.nely}",
            fine_result["compliance"],
            fine_result["volfrac"],
        ),
    ]

    for ax, rho, cfg, title, compliance, vf in panels:
        im = ax.imshow(
            rho,
            cmap="gray_r",
            origin="lower",
            vmin=0.0,
            vmax=1.0,
            extent=[0, cfg.lx, 0, cfg.ly],
            aspect="equal",
            interpolation="nearest",
        )
        ax.set_title(f"{title}\nC = {compliance:.6g}, VF = {vf:.4f}")
        ax.set_xlabel("x [in]")
        ax.set_ylabel("y [in]")
        fig.colorbar(im, ax=ax, fraction=0.025, pad=0.02, label="Density")

    fig.suptitle(f"Coarse-to-Fine Study: {problem_name}", fontsize=14)
    fig.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.show()
    plt.close(fig)


def plot_compliance_summary(summary_rows, out_path):
    labels = []
    values = []

    for row in summary_rows:
        problem = row["problem"]
        labels.extend([
            f"{problem}\ncoarse train",
            f"{problem}\ncoarse NN on fine",
            f"{problem}\ntrue fine train",
        ])
        values.extend([
            row["coarse_train_compliance"],
            row["coarse_nn_fine_compliance"],
            row["true_fine_train_compliance"],
        ])

    fig, ax = plt.subplots(figsize=(12, 5))
    ax.bar(np.arange(len(values)), values)
    ax.set_xticks(np.arange(len(values)))
    ax.set_xticklabels(labels, rotation=30, ha="right")
    ax.set_ylabel("Compliance")
    ax.set_title("Compliance comparison: coarse training, upsampled/reanalyzed NN, and true fine training")
    ax.grid(True, axis="y", alpha=0.3)
    fig.tight_layout()
    fig.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.show()
    plt.close(fig)


def run_coarse_to_fine_study():
    # --------------------------------------------------------
    # Base settings inherited from your current program.
    # Adjust only these few values when running the study.
    # --------------------------------------------------------
    base_cfg = Config()

    # Use width x height convention from your code: nelx x nely.
    # This corresponds to the user's requested 40x80 -> 100x200 if stated as height x width.
    coarse_nelx, coarse_nely = 80, 40
    fine_nelx, fine_nely = 200, 100

    # Define the physical domain from the coarse mesh and its element size.
    # With your current defaults this is 8 in x 4 in.
    lx_fixed = coarse_nelx * base_cfg.elem_size_x
    ly_fixed = coarse_nely * base_cfg.elem_size_y

    problems = ["Tip_loaded_cantilever", "MBB"]

    study_root = Path(base_cfg.out_dir) / "coarse_to_fine_validity_study"
    study_root.mkdir(parents=True, exist_ok=True)

    summary_rows = []

    print("=" * 90)
    print("COARSE-TO-FINE NN UPSAMPLING VALIDITY STUDY")
    print(f"Coarse mesh              : {coarse_nelx} x {coarse_nely}")
    print(f"Fine mesh                : {fine_nelx} x {fine_nely}")
    print(f"Fixed physical domain    : {lx_fixed:g} in x {ly_fixed:g} in")
    print(f"Coarse element size      : {lx_fixed/coarse_nelx:g} in x {ly_fixed/coarse_nely:g} in")
    print(f"Fine element size        : {lx_fixed/fine_nelx:g} in x {ly_fixed/fine_nely:g} in")
    print("=" * 90)

    for problem_name in problems:
        problem_tag = make_problem_tag(problem_name)
        problem_dir = study_root / problem_tag
        problem_dir.mkdir(parents=True, exist_ok=True)

        print("\n" + "#" * 90)
        print(f"PROBLEM: {problem_name}")
        print("#" * 90)

        coarse_cfg = make_mesh_cfg_from_domain(
            base_cfg=base_cfg,
            nelx=coarse_nelx,
            nely=coarse_nely,
            lx_fixed=lx_fixed,
            ly_fixed=ly_fixed,
            problem_name=problem_name,
            out_dir=str(problem_dir / "coarse_train"),
        )

        fine_cfg = make_mesh_cfg_from_domain(
            base_cfg=base_cfg,
            nelx=fine_nelx,
            nely=fine_nely,
            lx_fixed=lx_fixed,
            ly_fixed=ly_fixed,
            problem_name=problem_name,
            out_dir=str(problem_dir / "fine_train"),
        )

        # ----------------------------------------------------
        # 1. Train on coarse mesh
        # ----------------------------------------------------
        print("\n[1/3] Training coarse mesh model...")
        coarse_model, coarse_history, coarse_data, coarse_device, _ = train(coarse_cfg)
        coarse_result = get_training_final_result(
            coarse_model, coarse_history, coarse_cfg, coarse_data, coarse_device
        )

        # ----------------------------------------------------
        # 2. Sample the coarse-trained NN on the fine mesh and reanalyze
        # ----------------------------------------------------
        print("\n[2/3] Sampling coarse-trained NN on fine mesh and recomputing compliance...")
        upsample_result = evaluate_model_on_cfg(
            model=coarse_model,
            train_cfg=coarse_cfg,
            eval_cfg=fine_cfg,
            device=coarse_device,
        )

        # Optional binary check at the same target volume fraction.
        upsample_binary = threshold_to_target_vf(upsample_result["rho_grid"], fine_cfg.volfrac)
        upsample_binary_compliance, upsample_binary_vf = evaluate_density_grid_on_cfg(
            upsample_binary, fine_cfg
        )

        # ----------------------------------------------------
        # 3. Train directly on the fine mesh
        # ----------------------------------------------------
        print("\n[3/3] Training true fine mesh model...")
        fine_model, fine_history, fine_data, fine_device, _ = train(fine_cfg)
        fine_result = get_training_final_result(
            fine_model, fine_history, fine_cfg, fine_data, fine_device
        )

        # ----------------------------------------------------
        # Save comparison plot and numbers
        # ----------------------------------------------------
        comparison_path = problem_dir / f"{problem_tag}_coarse_to_fine_comparison.png"
        plot_three_way_comparison(
            problem_name=problem_name,
            coarse_cfg=coarse_cfg,
            fine_cfg=fine_cfg,
            coarse_result=coarse_result,
            upsample_result=upsample_result,
            fine_result=fine_result,
            out_path=comparison_path,
        )

        fine_gap_pct = 100.0 * (
            upsample_result["compliance"] - fine_result["compliance"]
        ) / max(abs(fine_result["compliance"]), 1e-12)

        row = {
            "problem": problem_name,
            "coarse_mesh": f"{coarse_cfg.nelx}x{coarse_cfg.nely}",
            "fine_mesh": f"{fine_cfg.nelx}x{fine_cfg.nely}",
            "domain_in": f"{lx_fixed:g}x{ly_fixed:g}",
            "coarse_element_size_in": f"{coarse_cfg.elem_size_x:g}x{coarse_cfg.elem_size_y:g}",
            "fine_element_size_in": f"{fine_cfg.elem_size_x:g}x{fine_cfg.elem_size_y:g}",
            "coarse_train_compliance": coarse_result["compliance"],
            "coarse_train_vf": coarse_result["volfrac"],
            "coarse_nn_fine_compliance": upsample_result["compliance"],
            "coarse_nn_fine_vf": upsample_result["volfrac"],
            "coarse_nn_fine_binary_compliance": upsample_binary_compliance,
            "coarse_nn_fine_binary_vf": upsample_binary_vf,
            "true_fine_train_compliance": fine_result["compliance"],
            "true_fine_train_vf": fine_result["volfrac"],
            "fine_compliance_gap_pct": fine_gap_pct,
            "comparison_plot": str(comparison_path),
        }
        summary_rows.append(row)

        print("\nSUMMARY FOR", problem_name)
        print(f"  Coarse train compliance            : {row['coarse_train_compliance']:.6g}")
        print(f"  Coarse NN reanalyzed on fine mesh  : {row['coarse_nn_fine_compliance']:.6g}")
        print(f"  True fine train compliance         : {row['true_fine_train_compliance']:.6g}")
        print(f"  Fine-mesh compliance gap           : {row['fine_compliance_gap_pct']:+.2f}%")
        print(f"  Optional binary fine compliance    : {row['coarse_nn_fine_binary_compliance']:.6g}")

        # Clean GPU/CPU memory before next problem.
        del coarse_model, fine_model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # --------------------------------------------------------
    # Save global summary
    # --------------------------------------------------------
    summary_csv = study_root / "coarse_to_fine_summary.csv"
    with open(summary_csv, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(summary_rows[0].keys()))
        writer.writeheader()
        writer.writerows(summary_rows)

    compliance_plot = study_root / "coarse_to_fine_compliance_summary.png"
    plot_compliance_summary(summary_rows, compliance_plot)

    print("\n" + "=" * 90)
    print("STUDY COMPLETE")
    print(f"Summary CSV              : {summary_csv}")
    print(f"Compliance summary plot  : {compliance_plot}")
    print("=" * 90)

    return summary_rows


# ============================================================
# Main run
# ============================================================

if __name__ == "__main__":
    summary_rows = run_coarse_to_fine_study()